import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const RELEASE_PRODUCT="ParkingMartin-G";
const RELEASE_VERSION="1.4.0";
const RELEASE_BUILD="2026.09.04.04";
const RELEASE_SOURCE_REVISION="f97484e55b4cebd67a04609013d08c232aed4f48";
function releaseAttestation(){return new Response(JSON.stringify({ok:true,product:RELEASE_PRODUCT,function:"modern-delivery-api",version:RELEASE_VERSION,build:RELEASE_BUILD,source_revision:RELEASE_SOURCE_REVISION}),{headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}

const BOT_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")!;const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;const SECRET_KEYS_JSON=Deno.env.get("SUPABASE_SECRET_KEYS");const LEGACY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const GOOGLE_VISION_KEY=Deno.env.get("GOOGLE_VISION_API_KEY")||Deno.env.get("GOOGLE_API_KEY")||null;const ORIGIN="https://jdlc86.github.io";
function key(){if(SECRET_KEYS_JSON){try{const p=JSON.parse(SECRET_KEYS_JSON);if(p?.default)return p.default;const v=Object.values(p??{})[0];if(typeof v==='string')return v}catch{}}if(LEGACY)return LEGACY;throw new Error('no_server_key')}function hdr(x:Record<string,string>={}){const k=key();return{apikey:k,Authorization:`Bearer ${k}`,...x}}function cors(){return{'Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Vary':'Origin'}}function json(x:any,s=200){return new Response(JSON.stringify(x),{status:s,headers:{'Content-Type':'application/json',...cors()}})}
function eq(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a[i]^b[i];return x===0}function hb(s:string){if(!/^[0-9a-f]{64}$/i.test(s))return null;const a=new Uint8Array(32);for(let i=0;i<32;i++)a[i]=parseInt(s.slice(i*2,i*2+2),16);return a}async function hmac(k:Uint8Array|string,m:string){const kb=typeof k==='string'?new TextEncoder().encode(k):k,ik=await crypto.subtle.importKey('raw',kb,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',ik,new TextEncoder().encode(m)))}async function auth(d:string){const p=new URLSearchParams(d),hash=p.get('hash')||'';p.delete('hash');const check=[...p.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>`${k}=${v}`).join('\n'),sec=await hmac('WebAppData',BOT_TOKEN),calc=await hmac(sec,check),given=hb(hash);if(!given||!eq(calc,given))throw new Error('invalid_init_data');const at=Number(p.get('auth_date')||0);if(!Number.isFinite(at)||Math.abs(Date.now()/1000-at)>900)throw new Error('expired_init_data');const u=JSON.parse(p.get('user')||'null');if(!u?.id)throw new Error('missing_user');return Number(u.id)}
async function rest(t:string,p:Record<string,string>){const u=new URL(`${SUPABASE_URL}/rest/v1/${t}`);for(const[k,v]of Object.entries(p))u.searchParams.set(k,v);const r=await fetch(u,{headers:hdr({Accept:'application/json'})});if(!r.ok)throw new Error(await r.text());return r.json()}async function one(t:string,p:Record<string,string>){return(await rest(t,{...p,limit:'1'}))[0]??null}async function insert(t:string,b:any,rep=true){const r=await fetch(`${SUPABASE_URL}/rest/v1/${t}`,{method:'POST',headers:hdr({'Content-Type':'application/json',Prefer:rep?'return=representation':'return=minimal'}),body:JSON.stringify(b)});if(!r.ok)throw new Error(await r.text());return rep?(await r.json())[0]:null}async function patch(t:string,f:Record<string,string>,b:any){const u=new URL(`${SUPABASE_URL}/rest/v1/${t}`);for(const[k,v]of Object.entries(f))u.searchParams.set(k,v);const r=await fetch(u,{method:'PATCH',headers:hdr({'Content-Type':'application/json',Prefer:'return=minimal'}),body:JSON.stringify(b)});if(!r.ok)throw new Error(await r.text())}
const norm=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,'');async function ctx(uid:number){const u=await one('telegram_users',{telegram_user_id:`eq.${uid}`,active:'eq.true',select:'telegram_user_id,role,username,first_name,last_name'});if(!u)throw new Error('not_authorized');let w=await one('workers',{telegram_user_id:`eq.${uid}`,active:'eq.true',select:'id,full_name'});if(!w){const full=[u.first_name,u.last_name].filter(Boolean).join(' ')||(u.username?`@${u.username}`:`Usuario ${uid}`);w=await insert('workers',{telegram_user_id:uid,full_name:full,role:u.role==='owner'||u.role==='admin'?'admin':'operator',active:true})}return{u,w}}async function vehicle(p:string){return one('vehicles',{normalized_plate:`eq.${p}`,select:'id,plate,status,current_lat,current_lng,current_accuracy_m,current_location_text,parked_at,last_updated_by'})}
async function rpc(name:string,body:any){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:hdr({'Content-Type':'application/json'}),body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||'rpc_failed');return d}
async function cancelActiveFlowSessions(flow:string,wid:string){const now=new Date().toISOString();await patch('operation_flow_sessions',{worker_id:`eq.${wid}`,flow_type:`eq.${flow}`,status:'eq.active'},{status:'cancelled',cancelled_at:now,updated_at:now})}
async function validateDeliveryTask(taskId:string,wid:string,plate:string){if(!taskId)return{task_id:null,booking_id:null};const t=await one('reservation_tasks',{id:`eq.${taskId}`,assigned_worker_id:`eq.${wid}`,task_type:'eq.delivery',status:'eq.assigned',select:'id,booking_id'});if(!t)throw new Error('flow_task_not_assigned');const booking=await one('parking_bookings',{id:`eq.${t.booking_id}`,select:'id,vehicle_plate_normalized,deleted_at'});if(!booking||booking.deleted_at||String(booking.vehicle_plate_normalized||'')!==plate)throw new Error('flow_task_plate_mismatch');return{task_id:t.id,booking_id:t.booking_id}}
async function createFlowSession(plate:string,v:any,w:any,uid:number,taskId:string){const binding=await validateDeliveryTask(taskId,w.id,plate);await cancelActiveFlowSessions('delivery',w.id);return insert('operation_flow_sessions',{flow_type:'delivery',normalized_plate:plate,vehicle_id:v.id,worker_id:w.id,telegram_user_id:uid,task_id:binding.task_id,booking_id:binding.booking_id,status:'active',current_step:'started'})}
async function requireFlowSession(id:string,plate:string,v:any,w:any,uid:number){if(!id)throw new Error('flow_session_required');const s=await one('operation_flow_sessions',{id:`eq.${id}`,select:'id,flow_type,normalized_plate,vehicle_id,worker_id,telegram_user_id,status,expires_at,task_id,booking_id'});if(!s)throw new Error('flow_session_not_found');if(s.status!=='active')throw new Error('flow_session_not_active');if(new Date(s.expires_at).getTime()<=Date.now())throw new Error('flow_session_expired');if(s.flow_type!=='delivery'||s.normalized_plate!==plate||s.vehicle_id!==v.id||s.worker_id!==w.id||Number(s.telegram_user_id)!==uid)throw new Error('flow_session_context_mismatch');return s}

function b64bytes(s:string){const raw=atob(s.replace(/^data:[^;]+;base64,/,'')),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a}function bytesB64(a:Uint8Array){let s='';for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s)}async function ocr(bytes:Uint8Array){if(!GOOGLE_VISION_KEY)return{detected:null,raw:null,error:'provider_not_configured'};const r=await fetch(`https://vision.googleapis.com/v1/images:annotate?key=${encodeURIComponent(GOOGLE_VISION_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requests:[{image:{content:bytesB64(bytes)},features:[{type:'TEXT_DETECTION',maxResults:20}]}]})});if(!r.ok)return{detected:null,raw:null,error:`vision_${r.status}`};const j=await r.json(),raw=String(j?.responses?.[0]?.fullTextAnnotation?.text??j?.responses?.[0]?.textAnnotations?.[0]?.description??''),c=(raw.toUpperCase().match(/[A-Z0-9][A-Z0-9\-\s]{3,11}[A-Z0-9]/g)??[]).map(norm).filter((x:string)=>x.length>=4&&x.length<=10);return{detected:c.sort((a:string,b:string)=>b.length-a.length)[0]??null,raw,error:null}}
async function savePlate(v:any,w:any,raw:string,sessionId:string){const bytes=b64bytes(raw);if(bytes.length<100||bytes.length>10_000_000)throw new Error('invalid_file_size');const path=`${v.id}/parking_exit/${Date.now()}-${crypto.randomUUID()}.jpg`;const sr=await fetch(`${SUPABASE_URL}/storage/v1/object/vehicle-evidence/${path}`,{method:'POST',headers:hdr({'Content-Type':'image/jpeg','x-upsert':'false'}),body:bytes});if(!sr.ok)throw new Error(await sr.text());const ev=await insert('vehicle_evidence',{vehicle_id:v.id,uploaded_by:w.id,stage:'parking_exit',evidence_type:'plate_photo',media_type:'photo',storage_path:path,mime_type:'image/jpeg',file_size:bytes.length,metadata:{source:'modern_delivery',purpose:'parking_exit_ocr',flow_session_id:sessionId}});return{ev,bytes}}
Deno.serve(async req=>{const requestUrl=new URL(req.url);if(req.method==='GET'&&requestUrl.searchParams.get("attest")==='1')return releaseAttestation();if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors()});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const origin=req.headers.get('Origin');if(origin&&origin!==ORIGIN)return json({ok:false,error:'origin_not_allowed'},403);const b=await req.json(),uid=await auth(String(b.initData||'')),{w}=await ctx(uid),action=String(b.action||'');if(action==='find'){const plate=norm(String(b.plate||''));if(plate.length<4||plate.length>12)return json({ok:false,error:'invalid_plate'},400);const v=await vehicle(plate);if(!v||v.status!=='parked')return json({ok:false,error:'not_parked'},404);const s=await createFlowSession(plate,v,w,uid,String(b.task_id||''));let worker=null;if(v.last_updated_by)worker=await one('workers',{id:`eq.${v.last_updated_by}`,select:'id,full_name'});return json({ok:true,flow_session_id:s.id,vehicle:{id:v.id,plate:v.plate,status:v.status,latitude:v.current_lat,longitude:v.current_lng,accuracy_m:v.current_accuracy_m,location_text:v.current_location_text,parked_at:v.parked_at,parked_by:worker?.full_name??null}})}
if(action==='plate_photo'){const plate=norm(String(b.plate||'')),v=await vehicle(plate);if(!v||v.status!=='parked')return json({ok:false,error:'not_parked'},409);const s=await requireFlowSession(String(b.flow_session_id||''),plate,v,w,uid);const saved=await savePlate(v,w,String(b.image_base64||''),s.id),o=await ocr(saved.bytes),det=o.detected?norm(o.detected):null,matched=!!det&&det===plate,vr=await insert('plate_verifications',{vehicle_id:v.id,worker_id:w.id,evidence_id:saved.ev.id,stage:'parking_exit',expected_plate:plate,detected_plate:det,ocr_raw_text:o.raw,result:matched?'matched':(det?'mismatch':'ocr_failed'),metadata:{ocr_provider:GOOGLE_VISION_KEY?'google_vision':'unconfigured',ocr_error:o.error,source:'modern_delivery',flow_session_id:s.id}});return json({ok:true,matched,detected_plate:det,verification_id:vr.id})}
if(action==='override'){const plate=norm(String(b.plate||'')),v=await vehicle(plate),id=String(b.verification_id||'');if(!v||!id)return json({ok:false,error:'invalid_override'},400);const s=await requireFlowSession(String(b.flow_session_id||''),plate,v,w,uid);const vr=await one('plate_verifications',{id:`eq.${id}`,vehicle_id:`eq.${v.id}`,stage:'eq.parking_exit',select:'id,metadata'});if(!vr)return json({ok:false,error:'verification_not_found'},404);if(String(vr.metadata?.flow_session_id||'')!==s.id)return json({ok:false,error:'verification_session_mismatch'},409);await patch('plate_verifications',{id:`eq.${id}`},{result:'overridden',override_reason:'operator_override',worker_id:w.id,metadata:{override_by_telegram_user_id:uid,overridden_at:new Date().toISOString(),source:'modern_delivery'}});return json({ok:true})}
if(action==='finish'){const plate=norm(String(b.plate||'')),v=await vehicle(plate);if(!v)return json({ok:false,error:'vehicle_not_found'},404);const s=await requireFlowSession(String(b.flow_session_id||''),plate,v,w,uid);const vid=String(b.verification_id||'');if(!vid)return json({ok:false,error:'verification_required'},409);const d=await rpc('complete_delivery_flow',{p_session_id:s.id,p_worker_id:w.id,p_telegram_user_id:uid,p_plate:plate,p_verification_id:vid});return json(d)}return json({ok:false,error:'invalid_action'},400)}catch(e){console.error(e);const m=String((e as Error)?.message||e);return json({ok:false,error:m},m==='not_authorized'?403:400)}});
