import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const RELEASE_PRODUCT="ParkingMartin-G";
const RELEASE_VERSION="1.4.0";
const RELEASE_BUILD="2026.09.04.04";
const RELEASE_SOURCE_REVISION="58a29bab7f716d99a19f0a1aa1b1c1d1e1f10203";
function releaseAttestation(){return new Response(JSON.stringify({ok:true,product:RELEASE_PRODUCT,function:"telegram-gateway",version:RELEASE_VERSION,build:RELEASE_BUILD,source_revision:RELEASE_SOURCE_REVISION}),{headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}

const BOT_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")!; const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!; const SECRET_KEYS_JSON=Deno.env.get("SUPABASE_SECRET_KEYS"); const LEGACY_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); const APP_URL="https://jdlc86.github.io/MartinGallardo_GPS/preview-modern/?v=20260904B04"; let webhookEnsured=false;
function sk(){if(SECRET_KEYS_JSON){try{const p=JSON.parse(SECRET_KEYS_JSON);if(p?.default)return p.default;const v=Object.values(p??{})[0];if(typeof v==='string')return v}catch{}}if(LEGACY_SERVICE_ROLE_KEY)return LEGACY_SERVICE_ROLE_KEY;throw new Error('No server key')} function hdr(extra:Record<string,string>={}){const k=sk();return{apikey:k,Authorization:`Bearer ${k}`,...extra}}
async function whSecret(){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(BOT_TOKEN));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')} async function tg(method:string,body:any){const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());const j=await r.json();if(j?.ok===false)throw new Error(JSON.stringify(j));return j} async function send(chat:number,text:string,reply_markup?:any){return tg('sendMessage',{chat_id:chat,text,...(reply_markup?{reply_markup}:{})})} async function answer(id:string,text:string){return tg('answerCallbackQuery',{callback_query_id:id,text})}
async function one(table:string,params:Record<string,string>){const u=new URL(`${SUPABASE_URL}/rest/v1/${table}`);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);u.searchParams.set('limit','1');const r=await fetch(u,{headers:hdr({Accept:'application/json'})});if(!r.ok)return null;return(await r.json())[0]??null} async function upsert(table:string,body:any,conflict:string){const u=new URL(`${SUPABASE_URL}/rest/v1/${table}`);u.searchParams.set('on_conflict',conflict);const r=await fetch(u,{method:'POST',headers:hdr({'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text())} async function delLive(id:number){const u=new URL(`${SUPABASE_URL}/rest/v1/worker_live_locations`);u.searchParams.set('telegram_user_id',`eq.${id}`);const r=await fetch(u,{method:'DELETE',headers:hdr({Prefer:'return=minimal'})});if(!r.ok)throw new Error(await r.text())}
async function activeUser(id:number){return one('telegram_users',{telegram_user_id:`eq.${id}`,active:'eq.true',select:'telegram_user_id,role,first_name,last_name,username'})} async function recentExpiredFlow(id:number){return one('parking_booking_notifications',{recipient_telegram_user_id:`eq.${id}`,notification_type:'eq.flow_session_expired',created_at:`gte.${new Date(Date.now()-24*60*60*1000).toISOString()}`,select:'id,created_at,payload',order:'created_at.desc'})} async function requestStatus(id:number){return one('telegram_access_requests',{telegram_user_id:`eq.${id}`,select:'telegram_user_id,status'})}
async function recordAccessRequest(from:any){const id=Number(from?.id);if(!Number.isFinite(id))return 'invalid';const prev=await requestStatus(id).catch(()=>null);const status=prev?.status==='rejected'?'rejected':'pending';await upsert('telegram_access_requests',{telegram_user_id:id,username:from?.username??null,first_name:from?.first_name??null,last_name:from?.last_name??null,last_seen_at:new Date().toISOString(),status},'telegram_user_id');return status}
async function handleUnknownUser(from:any,chatId:number|null,callbackId:string|null=null){const status=await recordAccessRequest(from);const text=status==='rejected'?'Tu solicitud de acceso está rechazada. Contacta con un administrador si crees que debe revisarse.':'Tu solicitud de acceso a ParkingMartin-G ha quedado registrada y está pendiente de autorización.';if(callbackId){try{await answer(callbackId,status==='rejected'?'Acceso no autorizado':'Solicitud registrada')}catch(e){console.error('access_request_callback',e)}}if(Number.isFinite(Number(chatId)))await send(Number(chatId),text);return new Response('ok')}
 async function worker(id:number){return one('workers',{telegram_user_id:`eq.${id}`,active:'eq.true',select:'id,full_name'})} function appKeyboard(){return{inline_keyboard:[[{text:'🚘 ABRIR PARKINGMARTIN-G',web_app:{url:APP_URL}}]]}} function displayName(msg:any,w:any,u:any){return w?.full_name||[msg?.from?.first_name,msg?.from?.last_name].filter(Boolean).join(' ')||[u?.first_name,u?.last_name].filter(Boolean).join(' ')||(msg?.from?.username?`@${msg.from.username}`:'Usuario')} function distanceM(a:number,b:number,c:number,d:number){const R=6371000,p=Math.PI/180,dLat=(c-a)*p,dLon=(d-b)*p;const x=Math.sin(dLat/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
async function saveLiveLocation(msg:any){const id=Number(msg?.from?.id),loc=msg?.location;if(!Number.isFinite(id)||!loc)return false;const lat=Number(loc.latitude),lng=Number(loc.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return false;const u=await activeUser(id);if(!u)return false;const w=await worker(id);const prev=await one('worker_live_locations',{telegram_user_id:`eq.${id}`,select:'telegram_user_id,latitude,longitude,accuracy_m,live_until,updated_at'});const now=new Date();const acc=Number.isFinite(Number(loc.horizontal_accuracy))?Number(loc.horizontal_accuracy):null;let liveUntil:any=prev?.live_until??null;if(Number.isFinite(Number(loc.live_period))&&Number(loc.live_period)>0){const base=Number(msg.date)||Math.floor(Date.now()/1000);liveUntil=new Date((base+Number(loc.live_period))*1000).toISOString()}if(prev){const elapsed=(now.getTime()-new Date(prev.updated_at).getTime())/1000;const moved=distanceM(Number(prev.latitude),Number(prev.longitude),lat,lng);const oldAcc=prev.accuracy_m==null?Infinity:Number(prev.accuracy_m);const accuracyImproved=acc!=null&&acc+3<oldAcc;if(elapsed<10&&moved<5&&!accuracyImproved)return true}await upsert('worker_live_locations',{telegram_user_id:id,worker_id:w?.id??null,full_name:displayName(msg,w,u),latitude:lat,longitude:lng,accuracy_m:acc,heading:Number.isFinite(Number(loc.heading))?Number(loc.heading):null,telegram_message_id:Number.isFinite(Number(msg.message_id))?Number(msg.message_id):null,chat_id:Number.isFinite(Number(msg.chat?.id))?Number(msg.chat.id):null,live_until:liveUntil,updated_at:now.toISOString()},'telegram_user_id');return true}
async function setup(){await tg('setWebhook',{url:`${SUPABASE_URL}/functions/v1/telegram-gateway`,secret_token:await whSecret(),allowed_updates:['message','edited_message','callback_query'],drop_pending_updates:false});await tg('setChatMenuButton',{menu_button:{type:'web_app',text:'Abrir ParkingMartin-G',web_app:{url:APP_URL}}});webhookEnsured=true}
const WELCOME=`👋 ¡Bienvenido a ParkingMartin-G!\n\nDesde aquí tienes acceso a todas las herramientas para gestionar el trabajo diario de forma rápida y coordinada.\n\n🚘 Pulsa «ABRIR PARKINGMARTIN-G» para acceder al Centro inteligente y realizar las operaciones del parking.\n\n📍 Compartir tu ubicación en tiempo real desde Telegram ayuda al equipo a saber dónde se encuentra cada compañero, mejorar la coordinación y responder con mayor rapidez cuando sea necesario. Puedes dejar de compartirla en cualquier momento.\n\n🤝 Cuanta mejor información tenga el equipo, más sencilla será la coordinación del trabajo.`;
const NEW_SESSION=`👋 Bienvenido a una nueva sesión de ParkingMartin-G.\n\nLa sesión anterior había caducado. Los datos que ya se registraron siguen guardados y no se mezclarán automáticamente con esta nueva sesión.\n\n🚘 Pulsa «ABRIR PARKINGMARTIN-G» para entrar de nuevo y revisar o reiniciar la operación de forma segura.`;
const ORIENT=`👋 ParkingMartin-G está a tu disposición.\n\n🚘 Utiliza el botón inferior para entrar al Centro inteligente.\n\n📍 Recuerda que compartir tu ubicación en tiempo real desde Telegram facilita la coordinación con tus compañeros. Puedes detenerla cuando quieras.`;
function chatOf(up:any){return up?.message?.chat||up?.edited_message?.chat||up?.callback_query?.message?.chat||null} function isGroupChat(chat:any){return chat?.type==='group'||chat?.type==='supergroup'}
Deno.serve(async(req)=>{const url=new URL(req.url);if(req.method==="GET"&&url.searchParams.get("attest")==="1")return releaseAttestation();if(req.method==='GET'&&url.searchParams.get('setup')==='1'){await setup();return new Response(JSON.stringify({ok:true,webhook:'telegram-gateway',ui:'production-miniapp-v15-group-guard',app_url:APP_URL,group_guard:true}),{headers:{'Content-Type':'application/json'}})}if(req.method!=='POST')return new Response('Method Not Allowed',{status:405});if(req.headers.get('X-Telegram-Bot-Api-Secret-Token')!==await whSecret())return new Response('Unauthorized',{status:401});if(!webhookEnsured){try{await setup()}catch(e){console.error('webhook_setup',e)}}const up=await req.json();const chat=chatOf(up);if(isGroupChat(chat)){const cb=up.callback_query;if(cb?.id){try{await answer(cb.id,'ParkingMartin-G funciona únicamente en chat privado.')}catch(e){console.error('group_callback',e)}}return new Response('ok')}
const edited=up.edited_message;if(edited?.location){const id=Number(edited?.from?.id),lp=Number(edited.location.live_period||0);try{if(Number.isFinite(id)&&lp===0)await delLive(id);else if(lp>0)await saveLiveLocation(edited)}catch(e){console.error('live_location_edit',e)}return new Response('ok')}const msgLoc=up.message;if(msgLoc?.location&&Number(msgLoc.location.live_period||0)>0){try{await saveLiveLocation(msgLoc)}catch(e){console.error('live_location',e)}return new Response('ok')}const cb=up.callback_query;if(cb?.from?.id){const id=Number(cb.from.id),chatId=Number(cb.message?.chat?.id),u=await activeUser(id);if(u){await answer(cb.id,'Abre ParkingMartin-G para continuar.');await send(chatId,ORIENT,appKeyboard());return new Response('ok')}return handleUnknownUser(cb.from,Number.isFinite(chatId)?chatId:null,String(cb.id??''))}const msg=up.message;if(msg?.from?.id&&msg?.chat?.id){const id=Number(msg.from.id),chatId=Number(msg.chat.id),u=await activeUser(id);if(u){const text=String(msg.text??'').trim();const expired=text==='/start'?await recentExpiredFlow(id).catch(()=>null):null;await send(chatId,text==='/start'?(expired?NEW_SESSION:WELCOME):ORIENT,appKeyboard());return new Response('ok')}return handleUnknownUser(msg.from,chatId)}return new Response('ok')});
