import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const RELEASE_PRODUCT="ParkingMartin-G";
const RELEASE_VERSION="1.4.0";
const RELEASE_BUILD="2026.09.04.04";
const RELEASE_SOURCE_REVISION="1234567890abcdef1234567890abcdef12345678";
function attest(){return new Response(JSON.stringify({ok:true,product:RELEASE_PRODUCT,function:"telegram-identity-sync",version:RELEASE_VERSION,build:RELEASE_BUILD,source_revision:RELEASE_SOURCE_REVISION}),{headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
const BOT_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")!,SUPABASE_URL=Deno.env.get("SUPABASE_URL")!,SECRET_KEYS_JSON=Deno.env.get("SUPABASE_SECRET_KEYS"),LEGACY_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),ORIGIN="https://jdlc86.github.io",MAX_AGE_SECONDS=600;
function serverKey(){if(SECRET_KEYS_JSON){try{const p=JSON.parse(SECRET_KEYS_JSON);if(typeof p?.default==="string")return p.default;const f=Object.values(p||{})[0];if(typeof f==="string")return f}catch{}}if(LEGACY_SERVICE_ROLE_KEY)return LEGACY_SERVICE_ROLE_KEY;throw new Error("no_server_key")}
function hdr(extra:Record<string,string>={}){const k=serverKey();return{apikey:k,Authorization:`Bearer ${k}`,...extra}}function cors(){return{"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS",Vary:"Origin"}}function json(v:unknown,s=200){return new Response(JSON.stringify(v),{status:s,headers:{"Content-Type":"application/json",...cors()}})}
async function hmac(k:Uint8Array|string,m:string){const b=typeof k==="string"?new TextEncoder().encode(k):k,r=b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength) as ArrayBuffer,i=await crypto.subtle.importKey("raw",r,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",i,new TextEncoder().encode(m)))}function hex(v:string){if(!/^[0-9a-f]{64}$/i.test(v))return null;const o=new Uint8Array(32);for(let i=0;i<32;i++)o[i]=parseInt(v.slice(i*2,i*2+2),16);return o}function eq(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0}
async function sha256Token(v:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)));return[...d].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function accessUser(token:string){if(!token)return null;const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/validate_miniapp_access_session`,{method:"POST",headers:hdr({"Content-Type":"application/json"}),body:JSON.stringify({p_token_hash:await sha256Token(token)})});if(!r.ok)throw new Error("access_session_validation_failed");const d=await r.json(),row=Array.isArray(d)?d[0]:d;if(!row?.telegram_user_id)throw new Error("expired_access_session");return Number(row.telegram_user_id)}
async function auth(initData:string,token:string){const p=new URLSearchParams(initData),given=hex(p.get("hash")||"");p.delete("hash");const check=[...p.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>`${k}=${v}`).join("\n"),calc=await hmac(await hmac("WebAppData",BOT_TOKEN),check);if(!given||!eq(calc,given))throw new Error("invalid_init_data");let u:any=null;try{u=JSON.parse(p.get("user")||"null")}catch{}const uid=Number(u?.id);if(!Number.isFinite(uid))throw new Error("missing_user");const sessionUid=await accessUser(token);if(sessionUid!=null){if(sessionUid!==uid)throw new Error("session_user_mismatch");return u}const t=Number(p.get("auth_date")||0);if(!Number.isFinite(t)||Math.abs(Date.now()/1000-t)>MAX_AGE_SECONDS)throw new Error("expired_init_data");return u}
async function sync(user:any){const id=Number(user.id),lookup=new URL(`${SUPABASE_URL}/rest/v1/telegram_users`);lookup.searchParams.set("telegram_user_id",`eq.${id}`);lookup.searchParams.set("select","telegram_user_id,active");lookup.searchParams.set("limit","1");const r=await fetch(lookup,{headers:hdr({Accept:"application/json"})});if(!r.ok)throw new Error("identity_lookup_failed");const rows=await r.json();if(!rows[0]||rows[0].active!==true)throw new Error("not_authorized");const username=typeof user.username==="string"&&user.username.trim()?user.username.trim():null,first=typeof user.first_name==="string"&&user.first_name.trim()?user.first_name.trim():null,last=typeof user.last_name==="string"&&user.last_name.trim()?user.last_name.trim():null,full=[first,last].filter(Boolean).join(" ")||(username?`@${username}`:`Usuario ${id}`);const tu=new URL(`${SUPABASE_URL}/rest/v1/telegram_users`);tu.searchParams.set("telegram_user_id",`eq.${id}`);let w=await fetch(tu,{method:"PATCH",headers:hdr({"Content-Type":"application/json",Prefer:"return=minimal"}),body:JSON.stringify({username,first_name:first,last_name:last})});if(!w.ok)throw new Error("identity_update_failed");const workers=new URL(`${SUPABASE_URL}/rest/v1/workers`);workers.searchParams.set("telegram_user_id",`eq.${id}`);w=await fetch(workers,{method:"PATCH",headers:hdr({"Content-Type":"application/json",Prefer:"return=minimal"}),body:JSON.stringify({full_name:full,updated_at:new Date().toISOString()})});if(!w.ok)throw new Error("worker_name_update_failed");return full}
Deno.serve(async req=>{const url=new URL(req.url);if(req.method==="GET"&&url.searchParams.get("attest")==="1")return attest();if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors()});if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);try{const o=req.headers.get("Origin");if(o&&o!==ORIGIN)return json({ok:false,error:"origin_not_allowed"},403);const b=await req.json(),u=await auth(String(b.initData||""),String(b.access_session_token||"")),name=await sync(u);return json({ok:true,name})}catch(e){const c=String((e as Error)?.message||e);return json({ok:false,error:c},["invalid_init_data","expired_init_data","expired_access_session","missing_user","not_authorized","session_user_mismatch"].includes(c)?403:400)}});
