import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const BOT_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")!;
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SECRET_KEYS_JSON=Deno.env.get("SUPABASE_SECRET_KEYS");
const LEGACY_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
function sk(){if(SECRET_KEYS_JSON){try{const p=JSON.parse(SECRET_KEYS_JSON);if(p?.default)return p.default;const v=Object.values(p??{})[0];if(typeof v==='string')return v}catch{}}if(LEGACY_SERVICE_ROLE_KEY)return LEGACY_SERVICE_ROLE_KEY;throw new Error('No server key')}
function hdr(extra:Record<string,string>={}){const k=sk();return{apikey:k,Authorization:`Bearer ${k}`,...extra}}
async function rows(table:string,params:Record<string,string>){const u=new URL(`${SUPABASE_URL}/rest/v1/${table}`);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);const r=await fetch(u,{headers:hdr({Accept:'application/json'})});if(!r.ok)throw new Error(await r.text());return r.json()}
async function rpc(name:string,body:any){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:hdr({'Content-Type':'application/json'}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}
async function tg(chat:number,text:string){const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chat,text})});const j=await r.json().catch(()=>null);if(!r.ok||j?.ok===false)throw new Error(`telegram_send_${r.status}`)}
function madridParts(){const f=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'});return Object.fromEntries(f.formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value])) as Record<string,string>}
function isoDate(y:number,m:number,d:number){return `${y.toString().padStart(4,'0')}-${m.toString().padStart(2,'0')}-${d.toString().padStart(2,'0')}`}
function addDays(date:string,n:number){const [y,m,d]=date.split('-').map(Number);const x=new Date(Date.UTC(y,m-1,d+n));return isoDate(x.getUTCFullYear(),x.getUTCMonth()+1,x.getUTCDate())}
function hm(ts:any){if(!ts)return'—';return new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit'}).format(new Date(ts))}
async function reserve(date:string,hour:number,id:number,reportScope:'personal'|'admin_team'){const r=await fetch(`${SUPABASE_URL}/rest/v1/performance_report_dispatches`,{method:'POST',headers:hdr({'Content-Type':'application/json',Prefer:'return=minimal'}),body:JSON.stringify({report_date:date,report_hour:hour,recipient_telegram_user_id:id,report_scope:reportScope})});if(r.status===409)return false;if(!r.ok)throw new Error(await r.text());return true}
async function unreserve(date:string,hour:number,id:number,reportScope:'personal'|'admin_team'){const u=new URL(`${SUPABASE_URL}/rest/v1/performance_report_dispatches`);u.searchParams.set('report_date',`eq.${date}`);u.searchParams.set('report_hour',`eq.${hour}`);u.searchParams.set('recipient_telegram_user_id',`eq.${id}`);u.searchParams.set('report_scope',`eq.${reportScope}`);await fetch(u,{method:'DELETE',headers:hdr()})}
function individualText(x:any,label:string){return `${label} · ${x.full_name}\n🚗 Recogidas: ${x.pickups}\n🅿️ Aparcados: ${x.parks}\n🔄 Reubicaciones: ${x.relocates||0}\n🔎 Búsquedas: ${x.lookups}\n🏁 Entregas: ${x.retrieves}\n⚠️ OCR ignorados: ${x.ocr_overrides}\n⏱️ Primera actividad: ${hm(x.first_activity)}\n⏱️ Última actividad: ${hm(x.last_activity)}\n📍 Ubicación compartida durante el turno: ${x.location_shared?'sí':'no'}`}
function adminText(data:any[],label:string){const totals=data.reduce((a,x)=>{a.pickups+=x.pickups;a.parks+=x.parks;a.relocates+=x.relocates||0;a.lookups+=x.lookups;a.retrieves+=x.retrieves;a.ocr+=x.ocr_overrides;a.ops+=x.total_operations;return a},{pickups:0,parks:0,relocates:0,lookups:0,retrieves:0,ocr:0,ops:0});let t=`${label} · Equipo\n🚗 Recogidas: ${totals.pickups}\n🅿️ Aparcados: ${totals.parks}\n🔄 Reubicaciones: ${totals.relocates}\n🔎 Búsquedas: ${totals.lookups}\n🏁 Entregas: ${totals.retrieves}\n⚠️ OCR ignorados: ${totals.ocr}\n📊 Operaciones totales: ${totals.ops}`;for(const x of data)t+=`\n\n${x.full_name}\n🚗 ${x.pickups} · 🅿️ ${x.parks} · 🔄 ${x.relocates||0} · 🔎 ${x.lookups} · 🏁 ${x.retrieves} · ⚠️ ${x.ocr_overrides}\n⏱️ ${hm(x.first_activity)}–${hm(x.last_activity)} · 📍 ${x.location_shared?'sí':'no'}`;return t}
Deno.serve(async req=>{if(req.method!=='POST')return new Response('Method Not Allowed',{status:405});try{const p=madridParts(),hour=Number(p.hour);if(![4,13,20].includes(hour))return new Response(JSON.stringify({ok:true,skipped:true,reason:'outside_schedule'}),{headers:{'Content-Type':'application/json'}});const today=`${p.year}-${p.month}-${p.day}`;const reportDate=hour===4?addDays(today,-1):today;const label=hour===4?'Resumen de ayer':'Resumen de hoy';const data=await rpc('get_daily_performance_report',{p_date:reportDate});const team=Array.isArray(data)?data:[];const operators=team.filter((x:any)=>x.role==='operario');let sent=0;for(const x of operators){const id=Number(x.telegram_user_id);if(!Number.isFinite(id))continue;if(!(await reserve(reportDate,hour,id,'personal')))continue;try{await tg(id,individualText(x,label));sent++}catch(e){await unreserve(reportDate,hour,id,'personal');console.error('personal',id,e)}}const admins=await rows('telegram_users',{active:'eq.true',role:'in.(owner,admin)',select:'telegram_user_id,role'});for(const a of admins){const id=Number(a.telegram_user_id);if(!Number.isFinite(id))continue;if(!(await reserve(reportDate,hour,id,'admin_team')))continue;try{await tg(id,adminText(team,label));sent++}catch(e){await unreserve(reportDate,hour,id,'admin_team');console.error('admin_team',id,e)}}return new Response(JSON.stringify({ok:true,report_date:reportDate,report_hour:hour,recipients_sent:sent}),{headers:{'Content-Type':'application/json'}})}catch(e){console.error(e);return new Response(JSON.stringify({ok:false,error:String((e as Error)?.message||e)}),{status:500,headers:{'Content-Type':'application/json'}})}});
