import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const RELEASE_PRODUCT="ParkingMartin-G";
const RELEASE_VERSION="1.4.0";
const RELEASE_BUILD="2026.09.04.04";
const RELEASE_SOURCE_REVISION="2fcf4f1cccf4323a0b15cb233c9981c964633d4e";
function releaseAttestation(){return new Response(JSON.stringify({ok:true,product:RELEASE_PRODUCT,function:"modern-relocate-api",version:RELEASE_VERSION,build:RELEASE_BUILD,source_revision:RELEASE_SOURCE_REVISION}),{headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}

const BOT_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")!;const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;const SECRET_KEYS_JSON=Deno.env.get("SUPABASE_SECRET_KEYS");const LEGACY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const ORIGIN="https://jdlc86.github.io";
function key(){if(SECRET_KEYS_JSON){try{const p=JSON.parse(SECRET_KEYS_JSON);if(p?.default)return p.default;const v=Object.values(p??{})[0];if(typeof v==='string')return v}catch{}}if(LEGACY)return LEGACY;throw new Error('no_server_key')}function hdr(extra:Record<string,string>={}){const k=key();return{apikey:k,Authorization:`Bearer ${k}`,...extra}}function cors(){return{"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}function json(x:any,s=200){return new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json",...cors()}})}
function eq(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a[i]^b[i];return x===0}function hexBytes(s:string){if(!/^[0-9a-f]{64}$/i.test(s))return null;const a=new Uint8Array(32);for(let i=0;i<32;i++)a[i]=parseInt(s.slice(i*2,i*2+2),16);return a}async function hmac(k:Uint8Array|string,m:string){const kb=typeof k==='string'?new TextEncoder().encode(k):k;const ik=await crypto.subtle.importKey('raw',kb,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',ik,new TextEncoder().encode(m)))}async function auth(initData:string){const p=new URLSearchParams(initData),hash=p.get('hash')||'';p.delete('hash');const check=[...p.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>`${k}=${v}`).join('\n');const sec=await hmac('WebAppData',BOT_TOKEN),calc=await hmac(sec,check),given=hexBytes(hash);if(!given||!eq(calc,given))throw new Error('invalid_init_data');const at=Number(p.get('auth_date')||0);if(!Number.isFinite(at)||Math.abs(Date.now()/1000-at)>86400)throw new Error('expired_init_data');const u=JSON.parse(p.get('user')||'null');if(!u?.id)throw new Error('missing_user');return Number(u.id)}
async function rest(t:string,p:Record<string,string>){const u=new URL(`${SUPABASE_URL}/rest/v1/${t}`);for(const[k,v]of Object.entries(p))u.searchParams.set(k,v);const r=await fetch(u,{headers:hdr({Accept:'application/json'})});if(!r.ok)throw new Error(await r.text());return r.json()}async function one(t:string,p:Record<string,string>){return(await rest(t,{...p,limit:'1'}))[0]??null}async function insert(t:string,b:any,rep=true){const r=await fetch(`${SUPABASE_URL}/rest/v1/${t}`,{method:'POST',headers:hdr({'Content-Type':'application/json',Prefer:rep?'return=representation':'return=minimal'}),body:JSON.stringify(b)});if(!r.ok)throw new Error(await r.text());return rep?(await r.json())[0]:null}async function patch(t:string,f:Record<string,string>,b:any){const u=new URL(`${SUPABASE_URL}/rest/v1/${t}`);for(const[k,v]of Object.entries(f))u.searchParams.set(k,v);const r=await fetch(u,{method:'PATCH',headers:hdr({'Content-Type':'application/json',Prefer:'return=minimal'}),body:JSON.stringify(b)});if(!r.ok)throw new Error(await r.text())}
const norm=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,'');async function ctx(uid:number){const u=await one('telegram_users',{telegram_user_id:`eq.${uid}`,active:'eq.true',select:'telegram_user_id,role'});if(!u)throw new Error('not_authorized');const w=await one('workers',{telegram_user_id:`eq.${uid}`,active:'eq.true',select:'id,full_name'});if(!w)throw new Error('not_authorized');return{u,w}}async function vehicle(p:string){return one('vehicles',{normalized_plate:`eq.${p}`,select:'id,plate,normalized_plate,status,current_lat,current_lng,current_accuracy_m,current_location_text,parked_at,updated_at'})}async function threshold(){return Number((await one('parking_config',{id:'eq.true',select:'default_accuracy_threshold_m'}))?.default_accuracy_threshold_m??15)}
async function rpc(name:string,body:any){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:hdr({'Content-Type':'application/json'}),body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||'rpc_failed');return d}
async function cancelActiveRelocate(wid:string,uid:number){const rows=await rest('operation_flow_sessions',{worker_id:`eq.${wid}`,flow_type:'eq.relocate',status:'eq.active',select:'id'});for(const s of rows)await rpc('cancel_operation_flow_session',{p_session_id:s.id,p_worker_id:wid,p_telegram_user_id:uid,p_flow_type:'relocate'})}
async function createRelocateSession(plate:string,v:any,w:any,uid:number){await cancelActiveRelocate(w.id,uid);return insert('operation_flow_sessions',{flow_type:'relocate',normalized_plate:plate,vehicle_id:v.id,worker_id:w.id,telegram_user_id:uid,status:'active',current_step:'started',expected_vehicle_updated_at:v.updated_at})}
async function requireRelocateSession(id:string,plate:string,v:any,w:any,uid:number){if(!id)throw new Error('flow_session_required');const s=await one('operation_flow_sessions',{id:`eq.${id}`,select:'id,flow_type,normalized_plate,vehicle_id,worker_id,telegram_user_id,status,expires_at,expected_vehicle_updated_at'});if(!s)throw new Error('flow_session_not_found');if(s.status!=='active')throw new Error('flow_session_not_active');if(new Date(s.expires_at).getTime()<=Date.now())throw new Error('flow_session_expired');if(s.flow_type!=='relocate'||s.normalized_plate!==plate||s.vehicle_id!==v.id||s.worker_id!==w.id||Number(s.telegram_user_id)!==uid)throw new Error('flow_session_context_mismatch');return s}

Deno.serve(async req=>{const requestUrl=new URL(req.url);if(req.method==="GET"&&requestUrl.searchParams.get("attest")==="1")return releaseAttestation();if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors()});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const origin=req.headers.get('Origin');if(origin&&origin!==ORIGIN)return json({ok:false,error:'origin_not_allowed'},403);const b=await req.json(),uid=await auth(String(b.initData||'')),{w}=await ctx(uid),action=String(b.action||'');
if(action==='start'){const plate=norm(String(b.plate||''));if(plate.length<4||plate.length>12)return json({ok:false,error:'invalid_plate'},400);const v=await vehicle(plate);if(!v)return json({ok:false,error:'vehicle_not_found'},404);if(v.status!=='parked')return json({ok:false,error:'not_parked'},409);const s=await createRelocateSession(plate,v,w,uid);return json({ok:true,plate,vehicle_id:v.id,flow_session_id:s.id,current:{latitude:v.current_lat,longitude:v.current_lng,accuracy_m:v.current_accuracy_m,location_text:v.current_location_text},parked_at:v.parked_at,accuracy_threshold_m:await threshold()})}
if(action==='finish'){const plate=norm(String(b.plate||'')),v=await vehicle(plate);if(!v)return json({ok:false,error:'vehicle_not_found'},404);const s=await requireRelocateSession(String(b.flow_session_id||''),plate,v,w,uid);const hasRawCoords=b.latitude!==null&&b.latitude!==undefined&&b.longitude!==null&&b.longitude!==undefined&&b.latitude!==''&&b.longitude!=='';const lat=hasRawCoords?Number(b.latitude):null,lng=hasRawCoords?Number(b.longitude):null,hasCoords=lat!==null&&lng!==null&&Number.isFinite(lat)&&Number.isFinite(lng)&&lat>=-90&&lat<=90&&lng>=-180&&lng<=180;if(hasRawCoords&&!hasCoords)return json({ok:false,error:'invalid_coordinates'},400);const accRaw=hasCoords?Number(b.accuracy_m):NaN,acc=Number.isFinite(accRaw)&&accRaw>=0?Math.min(accRaw,1500):null,th=await threshold(),txt=String(b.location_text||'').trim(),mode=hasCoords?'gps':'manual';if(!hasCoords&&!txt)return json({ok:false,error:'location_description_required'},409);if(hasCoords&&acc!=null&&acc>th&&!txt)return json({ok:false,error:'location_description_required',accuracy_threshold_m:th},409);const d=await rpc('complete_relocate_flow',{p_session_id:s.id,p_worker_id:w.id,p_telegram_user_id:uid,p_plate:plate,p_latitude:hasCoords?lat:null,p_longitude:hasCoords?lng:null,p_accuracy_m:acc,p_location_text:txt||null,p_location_mode:mode});return json(d)}return json({ok:false,error:'invalid_action'},400)}catch(e){console.error(e);const m=String((e as Error)?.message||e);return json({ok:false,error:m},m==='not_authorized'?403:400)}});
