import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const BOT_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")!;
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SECRET_KEYS_JSON=Deno.env.get("SUPABASE_SECRET_KEYS");
const LEGACY_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
const MAPS_KEY=Deno.env.get("GOOGLE_MAPS_API_KEY")||Deno.env.get("GOOGLE_ROUTES_API_KEY")||Deno.env.get("GOOGLE_API_KEY")||null;
const ORIGIN="https://jdlc86.github.io";
const MATRIX_URL="https://routes.googleapis.com/distanceMatrix/v2:computeRouteMatrix";
const MAX_AGE_SECONDS=86400;
class AppError extends Error{status:number;constructor(message:string,status=400){super(message);this.status=status}}
function serviceKey(){if(SECRET_KEYS_JSON){try{const p=JSON.parse(SECRET_KEYS_JSON);if(typeof p?.default==='string')return p.default;const x=Object.values(p||{})[0];if(typeof x==='string')return x}catch{}}if(LEGACY_SERVICE_ROLE_KEY)return LEGACY_SERVICE_ROLE_KEY;throw new AppError('no_server_key',500)}
function hdr(extra:Record<string,string>={}){const k=serviceKey();return{apikey:k,Authorization:`Bearer ${k}`,...extra}}
function cors(){return{"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS",Vary:"Origin"}}
function json(v:unknown,s=200){return new Response(JSON.stringify(v),{status:s,headers:{"Content-Type":"application/json",...cors()}})}
function eq(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0}
async function hmac(k:Uint8Array|string,m:string){const kb=typeof k==='string'?new TextEncoder().encode(k):k;const raw=kb.buffer.slice(kb.byteOffset,kb.byteOffset+kb.byteLength) as ArrayBuffer;const ik=await crypto.subtle.importKey('raw',raw,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',ik,new TextEncoder().encode(m)))}
function hex(v:string){if(!/^[0-9a-f]{64}$/i.test(v))return null;const o=new Uint8Array(32);for(let i=0;i<32;i++)o[i]=parseInt(v.slice(i*2,i*2+2),16);return o}
async function auth(initData:string){const p=new URLSearchParams(initData),sup=p.get('hash')||'';p.delete('hash');const chk=[...p.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>`${k}=${v}`).join('\n');const calc=await hmac(await hmac('WebAppData',BOT_TOKEN),chk),given=hex(sup);if(!given||!eq(calc,given))throw new AppError('invalid_init_data',403);const ad=Number(p.get('auth_date')||0);if(!Number.isFinite(ad)||Math.abs(Date.now()/1000-ad)>MAX_AGE_SECONDS)throw new AppError('expired_init_data',403);let u:any=null;try{u=JSON.parse(p.get('user')||'null')}catch{}const id=Number(u?.id);if(!Number.isFinite(id))throw new AppError('missing_user',403);return id}
async function table(name:string,params:Record<string,string>){const u=new URL(`${SUPABASE_URL}/rest/v1/${name}`);for(const [k,v] of Object.entries(params))u.searchParams.set(k,v);const r=await fetch(u,{headers:hdr({Accept:'application/json'})});if(!r.ok)throw new AppError(await r.text());return r.json()}
async function insert(name:string,body:unknown){const r=await fetch(`${SUPABASE_URL}/rest/v1/${name}`,{method:'POST',headers:hdr({'Content-Type':'application/json',Prefer:'return=representation'}),body:JSON.stringify(body)});if(!r.ok)throw new AppError(await r.text());return r.json()}
async function patch(name:string,filter:Record<string,string>,body:unknown){const u=new URL(`${SUPABASE_URL}/rest/v1/${name}`);for(const [k,v] of Object.entries(filter))u.searchParams.set(k,v);const r=await fetch(u,{method:'PATCH',headers:hdr({'Content-Type':'application/json',Prefer:'return=representation'}),body:JSON.stringify(body)});if(!r.ok)throw new AppError(await r.text());return r.json()}
async function upsert(name:string,conflict:string,body:unknown){const u=new URL(`${SUPABASE_URL}/rest/v1/${name}`);u.searchParams.set('on_conflict',conflict);const r=await fetch(u,{method:'POST',headers:hdr({'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify(body)});if(!r.ok)throw new AppError(await r.text())}
async function rpc(name:string,body:unknown){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:hdr({'Content-Type':'application/json'}),body:JSON.stringify(body)});const t=await r.text();if(!r.ok){let m=t;try{m=JSON.parse(t)?.message||t}catch{}throw new AppError(String(m),String(m).includes('changed')?409:400)}return t?JSON.parse(t):null}
async function requireWriter(actor:number,epoch:number){if(!Number.isSafeInteger(epoch)||epoch<1)throw new AppError('write_permission_changed',409);await rpc('parking_booking_require_writer',{p_actor_telegram_user_id:actor,p_writer_epoch:epoch})}
async function config(){return (await table('ai_dispatch_config',{id:'eq.1',select:'*',limit:'1'}))[0]}
async function candidateWorkers(){return table('workers',{active:'eq.true',role:'eq.operator',select:'id,telegram_user_id,full_name,role',order:'full_name.asc'})}
async function allActiveWorkers(){return table('workers',{active:'eq.true',select:'id,telegram_user_id,full_name,role',order:'full_name.asc'})}
function rawTerminal(v:unknown){const s=String(v||'').toUpperCase().replace(/\s+/g,'');if(s.includes('4S'))return'T4S';if(s.includes('T4')||s.includes('TERMINAL4'))return'T4';if(s.includes('T3')||s.includes('TERMINAL3'))return'T3';if(s.includes('T2')||s.includes('TERMINAL2'))return'T2';if(s.includes('T1')||s.includes('TERMINAL1'))return'T1';return s||'PARKING'}
function normalizeTerminal(v:unknown){const original=rawTerminal(v);return original==='T4S'?{original,operational:'T4',requires_review:true,review_reason:'terminal_t4s_normalized'}:{original,operational:original,requires_review:false,review_reason:null}}
function madridHour(d:Date){return Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',hour:'2-digit',hour12:false}).format(d))}
function localDay(d:Date){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function band(d:Date){const h=madridHour(d);return h<6?'MADRUGADA':h<10?'PUNTA_MANANA':h<16?'VALLE_DIA':h<20?'PUNTA_TARDE':'NOCHE'}
const BAND_HOURS:Record<string,number>={MADRUGADA:3,PUNTA_MANANA:8,VALLE_DIA:13,PUNTA_TARDE:18,NOCHE:22};
function madridOffsetMinutes(d:Date){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',timeZoneName:'shortOffset',hour:'2-digit'}).formatToParts(d);const z=parts.find(p=>p.type==='timeZoneName')?.value||'GMT+0',m=z.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);if(!m)return 0;const n=Number(m[2])*60+Number(m[3]||0);return m[1]==='-'?-n:n}
function nextBandDeparture(name:string){const now=new Date(),off=madridOffsetMinutes(now),ln=new Date(now.getTime()+off*60000),h=BAND_HOURS[name];let raw=Date.UTC(ln.getUTCFullYear(),ln.getUTCMonth(),ln.getUTCDate(),h),d=new Date(raw-madridOffsetMinutes(new Date(raw))*60000);if(+d<=Date.now()+300000){raw=Date.UTC(ln.getUTCFullYear(),ln.getUTCMonth(),ln.getUTCDate()+1,h);d=new Date(raw-madridOffsetMinutes(new Date(raw))*60000)}return d}
function sec(v:unknown){const m=String(v||'').match(/^([0-9]+(?:\.[0-9]+)?)s$/);return m?Math.round(Number(m[1])):null}
async function nodes(){return table('ai_dispatch_nodes',{code:'in.(PARKING,T1,T2,T3,T4)',select:'code,label,source_url,resolved_url,place_id,latitude,longitude,resolved_at',order:'code.asc'})}
function coordsFromUrl(url:string){const decoded=decodeURIComponent(url);let m=decoded.match(/@(-?\d{1,3}\.\d+),(-?\d{1,3}\.\d+)/);if(!m)m=decoded.match(/!3d(-?\d{1,3}\.\d+)!4d(-?\d{1,3}\.\d+)/);if(!m)return null;const latitude=Number(m[1]),longitude=Number(m[2]);return Number.isFinite(latitude)&&Number.isFinite(longitude)?{latitude,longitude}:null}
async function resolveNodes(){const rows=await nodes(),out=[];for(const n of rows){if(n.place_id||(Number.isFinite(Number(n.latitude))&&Number.isFinite(Number(n.longitude)))){out.push(n);continue}try{const r=await fetch(String(n.source_url),{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0'}}),url=r.url||String(n.source_url),c=coordsFromUrl(url);if(c){await patch('ai_dispatch_nodes',{code:`eq.${n.code}`},{resolved_url:url,latitude:c.latitude,longitude:c.longitude,resolved_at:new Date().toISOString(),updated_at:new Date().toISOString()});out.push({...n,resolved_url:url,...c})}else{await patch('ai_dispatch_nodes',{code:`eq.${n.code}`},{resolved_url:url,updated_at:new Date().toISOString()});out.push({...n,resolved_url:url})}}catch(e){console.error('resolve_node',n.code,e);out.push(n)}}return out}
function waypoint(n:any){if(n.place_id)return{placeId:n.place_id};if(Number.isFinite(Number(n.latitude))&&Number.isFinite(Number(n.longitude)))return{location:{latLng:{latitude:Number(n.latitude),longitude:Number(n.longitude)}}};throw new AppError(`route_node_unresolved:${n.code}`,503)}
async function computeMatrix(ns:any[],departure:Date){if(!MAPS_KEY)throw new AppError('google_routes_not_configured',503);const payload={origins:ns.map(n=>({waypoint:waypoint(n)})),destinations:ns.map(n=>({waypoint:waypoint(n)})),travelMode:'DRIVE',routingPreference:'TRAFFIC_AWARE',departureTime:departure.toISOString(),languageCode:'es-ES',units:'METRIC'};const r=await fetch(MATRIX_URL,{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':MAPS_KEY,'X-Goog-FieldMask':'originIndex,destinationIndex,duration,staticDuration,distanceMeters,status,condition'},body:JSON.stringify(payload)}),text=await r.text();if(!r.ok){console.error('google_routes',r.status,text.slice(0,1200));if(r.status===403)throw new AppError('google_routes_not_enabled',503);throw new AppError('google_routes_failed',502)}let a:any;try{a=JSON.parse(text)}catch{throw new AppError('google_routes_invalid_response',502)}return Array.isArray(a)?a:[]}
function routeBandList(value:any){const valid=new Set(Object.keys(BAND_HOURS));const raw=Array.isArray(value)?value.map(String):[];const out=[...new Set(raw.filter(x=>valid.has(x)))];return out.length?out:Object.keys(BAND_HOURS)}
function requestedTerminals(value:any){const valid=new Set(['T1','T2','T3','T4']);const raw=Array.isArray(value)?value.map((x:any)=>normalizeTerminal(x).operational):[];const out=[...new Set(raw.filter((x:string)=>valid.has(x)))];return out.length?out:['T1','T2','T3','T4']}
function haversineMeters(a:any,b:any){const la1=Number(a?.latitude),lo1=Number(a?.longitude),la2=Number(b?.latitude),lo2=Number(b?.longitude);if(![la1,lo1,la2,lo2].every(Number.isFinite))return null;const R=6371000,toRad=(x:number)=>x*Math.PI/180,dLat=toRad(la2-la1),dLon=toRad(lo2-lo1),x=Math.sin(dLat/2)**2+Math.cos(toRad(la1))*Math.cos(toRad(la2))*Math.sin(dLon/2)**2;return Math.round(2*R*Math.asin(Math.sqrt(x)))}
function dynamicEstimate(a:any,b:any){const straight=haversineMeters(a,b);if(!straight)return{seconds:2100,distance_m:0,source:'emergency_default'};const road=Math.max(1000,Math.round(straight*1.28)),seconds=Math.max(600,Math.round(road/1000/32*3600+240));return{seconds,distance_m:road,source:'estimated_distance'}}
async function refreshRoutes(force=false,bandInput:any=null,terminalInput:any=null){
  const cfg=await config(),ns=await resolveNodes(),bad=ns.filter((n:any)=>!n.place_id&&(!Number.isFinite(Number(n.latitude))||!Number.isFinite(Number(n.longitude))));
  if(bad.length)return{matrix_ready:false,reason:'route_nodes_unresolved',unresolved:bad.map((n:any)=>n.code),refreshed:0,degraded:false};
  const bands=routeBandList(bandInput),terminals=requestedTerminals(terminalInput),parking=ns.find((n:any)=>n.code==='PARKING'),byCode=new Map(ns.map((n:any)=>[n.code,n]));
  const old=await table('ai_dispatch_route_matrix',{select:'origin,destination,time_band,fetched_at,baseline_duration_s,current_duration_s,distance_m,source'});
  let refreshed=0,fallbackUsed=0,cachedUsed=0;const warnings:any[]=[];
  for(const bn of bands){
    const dep=nextBandDeparture(bn),near=+dep-Date.now()<=86400000,ttl=(near?Number(cfg.ttl_near_hours):Number(cfg.ttl_future_hours))*3600000;
    const needed=terminals.flatMap((t:string)=>[['PARKING',t],[t,'PARKING']]);
    const rows=old.filter((x:any)=>x.time_band===bn);
    const required=needed.map(([o,d])=>rows.find((x:any)=>x.origin===o&&x.destination===d)).filter(Boolean);
    const fresh=required.length===needed.length&&required.every((x:any)=>{
      const age=Date.now()-Date.parse(x.fetched_at);
      const effectiveTtl=x.source==='google_routes'?ttl:Math.min(ttl,30*60000);
      return Boolean(x.current_duration_s)&&age<effectiveTtl;
    });
    if(fresh&&!force){cachedUsed+=needed.length;continue}
    let googleOk=false;
    if(MAPS_KEY){
      try{
        const selected=[parking,...terminals.map((t:string)=>byCode.get(t)).filter(Boolean)];
        const mx=await computeMatrix(selected,dep),writes:any[]=[];
        for(const e of mx){
          const oi=Number(e.originIndex),di=Number(e.destinationIndex);
          if(oi===di||e.condition==='ROUTE_NOT_FOUND'||e.status?.code)continue;
          const origin=selected[oi]?.code,destination=selected[di]?.code;
          if(origin!=='PARKING'&&destination!=='PARKING')continue;
          const dur=sec(e.duration),stat=sec(e.staticDuration),dist=Number(e.distanceMeters);
          if(!origin||!destination||!dur||!Number.isFinite(dist))continue;
          const prior=rows.find((x:any)=>x.origin===origin&&x.destination===destination),base=Number(prior?.baseline_duration_s)||stat||dur,dev=base?Number(((dur-base)/base).toFixed(4)):0;
          writes.push({origin,destination,time_band:bn,distance_m:Math.round(dist),baseline_duration_s:base,current_duration_s:dur,deviation_pct:dev,is_anomaly:Math.abs(dev)>=0.25,source:'google_routes',fetched_at:new Date().toISOString()});
        }
        if(writes.length){await upsert('ai_dispatch_route_matrix','origin,destination,time_band',writes);refreshed+=writes.length}
        googleOk=writes.length>=needed.length;
      }catch(e){console.error('route_preflight_google',bn,e);warnings.push({band:bn,reason:String((e as Error)?.message||e)})}
    }else warnings.push({band:bn,reason:'google_routes_not_configured'});
    if(googleOk)continue;
    const fallbackWrites:any[]=[];
    for(const [origin,destination] of needed){
      const prior=rows.find((x:any)=>x.origin===origin&&x.destination===destination);
      if(prior?.current_duration_s){
        const ageHours=Math.max(0,(Date.now()-Date.parse(prior.fetched_at||0))/3600000);
        if(ageHours<=2){cachedUsed++;continue}
        const ref=Math.max(Number(prior?.baseline_duration_s)||0,Number(prior.current_duration_s)||0);
        const penalty=ageHours>48?1.35:ageHours>12?1.25:1.15;
        fallbackWrites.push({origin,destination,time_band:bn,distance_m:Number(prior?.distance_m)||0,baseline_duration_s:Number(prior?.baseline_duration_s)||ref,current_duration_s:Math.ceil(ref*penalty),deviation_pct:Number((penalty-1).toFixed(4)),is_anomaly:false,source:'cached_stale',fetched_at:prior.fetched_at||new Date().toISOString()});
        continue;
      }
      const base=Number(prior?.baseline_duration_s);
      if(base>0){
        fallbackWrites.push({origin,destination,time_band:bn,distance_m:Number(prior?.distance_m)||0,baseline_duration_s:base,current_duration_s:Math.ceil(base*1.20),deviation_pct:0.20,is_anomaly:false,source:'historical_baseline',fetched_at:new Date().toISOString()});
        continue;
      }
      const est=dynamicEstimate(byCode.get(origin),byCode.get(destination));
      fallbackWrites.push({origin,destination,time_band:bn,distance_m:est.distance_m,baseline_duration_s:est.seconds,current_duration_s:est.seconds,deviation_pct:0,is_anomaly:false,source:est.source,fetched_at:new Date().toISOString()});
    }
    if(fallbackWrites.length){await upsert('ai_dispatch_route_matrix','origin,destination,time_band',fallbackWrites);fallbackUsed+=fallbackWrites.length}
  }
  const finalRows=await table('ai_dispatch_route_matrix',{select:'origin,destination,time_band,current_duration_s,source,fetched_at'});
  const missing:any[]=[];
  for(const bn of bands)for(const t of terminals)for(const [o,d] of [['PARKING',t],[t,'PARKING']])if(!finalRows.some((x:any)=>x.time_band===bn&&x.origin===o&&x.destination===d&&Number(x.current_duration_s)>0))missing.push({origin:o,destination:d,time_band:bn});
  return{matrix_ready:missing.length===0,refreshed,fallback_used:fallbackUsed,cached_used:cachedUsed,degraded:warnings.length>0||fallbackUsed>0,warnings,missing,required_bands:bands,required_terminals:terminals};
}
async function matrix(){const rows=await table('ai_dispatch_route_matrix',{origin:'neq.T4S',destination:'neq.T4S',select:'origin,destination,time_band,current_duration_s,distance_m,is_anomaly,fetched_at'}),m=new Map<string,any>();for(const r of rows)m.set(`${r.origin}>${r.destination}@${r.time_band}`,r);return m}
function road(from:string,to:string,at:Date,cfg:any,m:Map<string,any>){if(from===to)return{minutes:0,distance_m:0,approx:false};const r=m.get(`${from}>${to}@${band(at)}`);if(r?.current_duration_s){const base=Math.ceil(Number(r.current_duration_s)/60),unc=Math.max(Number(cfg.road_uncertainty_min_minutes),Math.ceil(base*Number(cfg.road_uncertainty_pct)));return{minutes:base+unc,distance_m:Number(r.distance_m)||0,approx:false,anomaly:Boolean(r.is_anomaly)}}return{minutes:25,distance_m:0,approx:true}}
const DIRECT:Record<string,number>={'T1>T2':2,'T1>T4':10,'T2>T1':5,'T2>T4':8,'T3>T2':2,'T3>T1':7,'T4>T3':8,'T4>T2':10,'T4>T1':15};
function shuttleWait(at:Date,cfg:any){const h=madridHour(at),start=Number(cfg.terminal_shuttle_day_start_hour),end=Number(cfg.terminal_shuttle_day_end_hour),day=Number(cfg.terminal_shuttle_wait_day_minutes),night=Number(cfg.terminal_shuttle_wait_night_minutes);const inDay=start<end?(h>=start&&h<end):(h>=start||h<end);return inDay?day:night}
function terminalTransfer(from:string,to:string,at:Date,cfg:any){if(from===to)return{minutes:0,steps:[] as any[]};const access=Number(cfg.terminal_shuttle_access_minutes),d=DIRECT[`${from}>${to}`];if(d!=null){const wait=shuttleWait(at,cfg);return{minutes:access+wait+d,steps:[{mode:'shuttle',from,to,access_minutes:access,wait_minutes:wait,ride_minutes:d}]}}if((from==='T1'||from==='T2')&&to==='T3'){const first=DIRECT[`${from}>T4`],wait1=shuttleWait(at,cfg),mid=new Date(+at+(access+wait1+first)*60000),second=DIRECT['T4>T3'],wait2=shuttleWait(mid,cfg);return{minutes:access+wait1+first+wait2+second,steps:[{mode:'shuttle',from,to:'T4',access_minutes:access,wait_minutes:wait1,ride_minutes:first},{mode:'shuttle',from:'T4',to:'T3',access_minutes:0,wait_minutes:wait2,ride_minutes:second}]}}if(from==='T3'&&to==='T4'){const first=7,wait1=shuttleWait(at,cfg),mid=new Date(+at+(access+wait1+first)*60000),second=10,wait2=shuttleWait(mid,cfg);return{minutes:access+wait1+first+wait2+second,steps:[{mode:'shuttle',from:'T3',to:'T1',access_minutes:access,wait_minutes:wait1,ride_minutes:first},{mode:'shuttle',from:'T1',to:'T4',access_minutes:0,wait_minutes:wait2,ride_minutes:second}]}}return{minutes:35,steps:[{mode:'shuttle_estimated',from,to}]}}
function taskMap(raw:any){const b=raw.parking_bookings||{},src=raw.task_type==='pickup'?b.pickup_terminal:b.return_terminal,n=normalizeTerminal(src);return{id:raw.id,booking_id:raw.booking_id,type:raw.task_type,scheduled_at:raw.scheduled_at,terminal:n.operational,terminal_original:n.original,requires_review:n.requires_review,review_reason:n.review_reason,plate:b.vehicle_plate,customer_name:b.customer_name,version:Number(raw.version),assigned_worker:raw.workers?{id:raw.workers.id,full_name:raw.workers.full_name,telegram_user_id:raw.workers.telegram_user_id}:null,status:raw.status}}
async function tasks(start:string,end:string){const rows=await table('reservation_tasks',{status:'in.(unassigned,assigned)',scheduled_at:`gte.${start}`,and:`(scheduled_at.lt.${end})`,select:'id,booking_id,task_type,scheduled_at,assigned_worker_id,status,version,parking_bookings!inner(id,pickup_terminal,return_terminal,vehicle_plate,customer_name,deleted_at),workers(id,telegram_user_id,full_name)','parking_bookings.deleted_at':'is.null',order:'scheduled_at.asc'});return rows.map(taskMap)}
function timing(t:any,cfg:any,mx:Map<string,any>){const sched=new Date(t.scheduled_at),target=new Date(+sched-Number(cfg.target_early_minutes)*60000);if(t.type==='delivery'){const r=road('PARKING',t.terminal,target,cfg,mx),depart=new Date(+target-r.minutes*60000),end=new Date(+sched+Number(cfg.operation_minutes)*60000);return{...t,sched,target,road:r,car_depart:depart,car_arrive:target,worker_end:end,start_node:'PARKING',end_node:t.terminal}}const r=road(t.terminal,'PARKING',new Date(+sched+Number(cfg.operation_minutes)*60000),cfg,mx),carDepart=new Date(+sched+Number(cfg.operation_minutes)*60000),end=new Date(+carDepart+r.minutes*60000);return{...t,sched,target,road:r,car_depart:carDepart,car_arrive:end,worker_end:end,start_node:t.terminal,end_node:'PARKING'}}
function prevDirect(prev:any,cur:any,cfg:any){if(!prev)return cur.type==='delivery'?{kind:'direct',ready:new Date(0),cost:0}:{kind:'ride_out',ready:new Date(0),cost:600};if(localDay(prev.sched)!==localDay(cur.sched))return cur.type==='delivery'?{kind:'direct',ready:new Date(0),cost:0}:{kind:'ride_out',ready:new Date(0),cost:600};if(prev.type==='pickup'&&cur.type==='delivery'){if(+prev.worker_end<=+cur.car_depart)return{kind:'direct',ready:prev.worker_end,cost:10};return{kind:'infeasible',reason:'pickup_to_delivery_overlap'}}if(prev.type==='delivery'&&cur.type==='pickup'){const tr=terminalTransfer(prev.terminal,cur.terminal,prev.worker_end,cfg);if(+prev.worker_end+tr.minutes*60000<=+cur.target)return{kind:'terminal_transfer',ready:prev.worker_end,cost:tr.minutes,transfer:tr};return{kind:'infeasible',reason:'delivery_to_pickup_overlap'}}if(prev.type==='pickup'&&cur.type==='pickup'){if(+prev.worker_end<+cur.target)return{kind:'ride_out',ready:prev.worker_end,cost:600};return{kind:'infeasible',reason:'pickup_to_pickup_overlap'}}if(prev.type==='delivery'&&cur.type==='delivery'){if(+prev.worker_end<+cur.car_depart)return{kind:'ride_in',ready:prev.worker_end,cost:600};return{kind:'infeasible',reason:'delivery_to_delivery_overlap'}}return{kind:'infeasible',reason:'unknown_transition'}}
function movementContract(t:any,wid:string,seats:any[],needs:any[]){const tr=t.transition_from_prev||{kind:'direct'};const need=needs.find((n:any)=>n.worker_id===wid&&n.task.id===t.id);let positioning:any={kind:tr.kind,ready:tr.ready?new Date(tr.ready).toISOString():null,transfer:tr.transfer||null};if(need?.matched){const s=seats.find((x:any)=>x.id===need.matched.seat_id);positioning={kind:'ride_with_worker',direction:need.direction,ready:need.ready?new Date(need.ready).toISOString():null,depart_at:s?.depart?new Date(s.depart).toISOString():null,arrive_at:need.matched.arrival||null,from:s?.from||null,to:s?.to||null,target_terminal:t.terminal,driver_worker_id:need.matched.driver_worker_id,driver_name:need.matched.driver_name,driver_task_id:need.matched.driver_task_id,vehicle_plate:s?.task?.plate||null,terminal_transfer:need.matched.transfer||null}}const seat=seats.find((s:any)=>s.task.id===t.id);const passenger=seat?.passenger?{worker_id:seat.passenger.worker_id,worker_name:seat.passenger.worker_name,target_task_id:seat.passenger.target_task_id,from:seat.from,to:seat.to,depart_at:seat.depart?new Date(seat.depart).toISOString():null,arrive_at:seat.arrive?new Date(seat.arrive).toISOString():null,terminal_transfer:seat.passenger.transfer||null}:null;return{...t,positioning_from_prev:positioning,passenger_transport:passenger}}
function buildPhysical(all:any[],candidates:any[],active:any[],cfg:any,mx:Map<string,any>){const workerById=new Map(active.map((w:any)=>[w.id,w])),ag=new Map<string,any[]>();for(const w of active)ag.set(w.id,[]);const fixed=all.filter((t:any)=>t.assigned_worker).map((t:any)=>timing(t,cfg,mx));for(const t of fixed){if(!ag.has(t.assigned_worker.id))ag.set(t.assigned_worker.id,[]);ag.get(t.assigned_worker.id)!.push({...t,fixed:true})}for(const a of ag.values())a.sort((x,y)=>+x.sched-+y.sched);const free=all.filter((t:any)=>!t.assigned_worker).map((t:any)=>timing(t,cfg,mx));const unassigned:any[]=[];for(const cur of free){let best:any=null;for(const w of candidates){const a=ag.get(w.id)||[],prev=[...a].filter((x:any)=>+x.sched<=+cur.sched).pop(),next=a.find((x:any)=>+x.sched>+cur.sched);const p=prevDirect(prev,cur,cfg);if(p.kind==='infeasible')continue;const n=next?prevDirect(cur,next,cfg):{kind:'direct',cost:0};if(n.kind==='infeasible')continue;const score=Number(p.cost||0)+Number(n.cost||0)+a.length*20,c={w,score,transition:p};if(!best||score<best.score)best=c}if(!best){unassigned.push({task_id:cur.id,reason:'no_physical_driver_sequence'});continue}ag.get(best.w.id)!.push({...cur,fixed:false});ag.get(best.w.id)!.sort((x:any,y:any)=>+x.sched-+y.sched)}
const seats:any[]=[],needs:any[]=[];for(const [wid,a0] of ag){const a=[...a0].sort((x:any,y:any)=>+x.sched-+y.sched);let prev:any=null;for(const t of a){const trans=prevDirect(prev,t,cfg);t.transition_from_prev=trans;if(t.type==='delivery')seats.push({id:`seat:${t.id}`,direction:'out',driver_worker_id:wid,task:t,depart:t.car_depart,arrive:t.car_arrive,from:'PARKING',to:t.terminal,used:false});else seats.push({id:`seat:${t.id}`,direction:'in',driver_worker_id:wid,task:t,depart:t.car_depart,arrive:t.car_arrive,from:t.terminal,to:'PARKING',used:false});if(trans.kind==='ride_out')needs.push({id:`need:${wid}:${t.id}`,direction:'out',worker_id:wid,task:t,ready:prev?prev.worker_end:new Date(0),target_terminal:t.terminal,arrive_by:t.target,matched:null});if(trans.kind==='ride_in')needs.push({id:`need:${wid}:${t.id}`,direction:'in',worker_id:wid,task:t,ready:prev.worker_end,origin_terminal:prev.terminal,arrive_by:t.car_depart,matched:null});prev=t}}
const name=(id:string)=>workerById.get(id)?.full_name||'Operario';for(const need of needs.sort((a,b)=>+a.arrive_by-+b.arrive_by)){let best:any=null;for(const s of seats){if(s.used||s.direction!==need.direction||s.driver_worker_id===need.worker_id)continue;if(need.direction==='out'){if(+s.depart<+need.ready)continue;const tr=terminalTransfer(s.to,need.target_terminal,s.arrive,cfg),arr=new Date(+s.arrive+tr.minutes*60000);if(+arr>+need.arrive_by)continue;const score=tr.minutes+(+need.arrive_by-+arr)/60000;if(!best||score<best.score)best={s,tr,arr,score}}else{const tr=terminalTransfer(need.origin_terminal,s.from,need.ready,cfg),reach=new Date(+need.ready+tr.minutes*60000);if(+reach>+s.depart||+s.arrive>+need.arrive_by)continue;const score=tr.minutes+(+need.arrive_by-+s.arrive)/60000;if(!best||score<best.score)best={s,tr,arr:s.arrive,score}}}if(best){best.s.used=true;need.matched={seat_id:best.s.id,driver_worker_id:best.s.driver_worker_id,driver_name:name(best.s.driver_worker_id),driver_task_id:best.s.task.id,transfer:best.tr,arrival:best.arr.toISOString()};best.s.passenger={worker_id:need.worker_id,worker_name:name(need.worker_id),need_id:need.id,target_task_id:need.task.id,transfer:best.tr}}}
const unmatched=needs.filter((n:any)=>!n.matched),assignments:any[]=[],reports:any={},reviews=all.filter((t:any)=>t.requires_review).map((t:any)=>({task_id:t.id,booking_id:t.booking_id,reason:t.review_reason,original_terminal:t.terminal_original,operational_terminal:t.terminal,message:'Terminal original T4S normalizada a T4 para la operativa del vehículo. Revisar la reserva antes de ejecutar.'}));for(const [wid,a0] of ag){const worker=workerById.get(wid)||{id:wid,full_name:'Operario',telegram_user_id:null},items=[...a0].sort((x:any,y:any)=>+x.sched-+y.sched);for(const t of items)if(!t.fixed)assignments.push({task_id:t.id,version:t.version,worker_id:wid});const enriched=items.map((t:any)=>movementContract(t,wid,seats,needs));reports[wid]={worker,text:physicalReport(worker,items,seats,needs,cfg),items:enriched}}
return{assignments,reports,fixed_count:fixed.length,unassigned,reviews,requires_review:reviews.length>0,physical_feasible:unassigned.length===0&&unmatched.length===0,unmatched_needs:unmatched.map((n:any)=>({worker_id:n.worker_id,task_id:n.task.id,direction:n.direction,arrive_by:n.arrive_by.toISOString()})),movement_contract_version:'v2_shuttle_config'}}
function hm(d:Date){return new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit'}).format(d)}
function physicalReport(worker:any,items:any[],seats:any[],needs:any[],cfg:any){const out=[`📅 Plan operativo · ${worker.full_name}`];for(const t of items){if(t.requires_review)out.push('⚠️ Terminal original T4S normalizada a T4 para la operativa del vehículo. Revisar la reserva antes de ejecutar.');const need=needs.find((n:any)=>n.worker_id===worker.id&&n.task.id===t.id);if(need?.matched){const s=seats.find((x:any)=>x.id===need.matched.seat_id);if(need.direction==='out'){out.push(`👥 ${hm(s.depart)} · Salir del Parking con ${need.matched.driver_name} en ${s.task.plate||'vehículo'} → ${s.to}`);if(need.matched.transfer?.minutes)out.push(`🚌 Desde ${s.to} desplazarse a ${t.terminal} por terminales`)}else{if(need.matched.transfer?.minutes)out.push(`🚌 Desplazarse desde ${need.origin_terminal} a ${s.from}`);out.push(`👥 ${hm(s.depart)} · Regresar al Parking con ${need.matched.driver_name} en ${s.task.plate||'vehículo'}`)}}if(t.type==='delivery'){out.push(`↗ ${hm(t.car_depart)} · Salir del Parking · ${t.plate||'—'} → ${t.terminal}`);const seat=seats.find((s:any)=>s.task.id===t.id);if(seat?.passenger)out.push(`👥 Recoger en Parking a ${seat.passenger.worker_name}; viaja contigo hasta ${t.terminal}`);out.push(`${hm(t.sched)} · ENTREGA · ${t.terminal} · ${t.plate||'—'} · ${t.customer_name||'—'}`);out.push(`${hm(t.worker_end)} · Fin operación en ${t.terminal}`)}else{out.push(`${hm(t.sched)} · RECOGIDA · ${t.terminal} · ${t.plate||'—'} · ${t.customer_name||'—'}`);const seat=seats.find((s:any)=>s.task.id===t.id);if(seat?.passenger)out.push(`👥 Antes de salir, recoger a ${seat.passenger.worker_name} en ${t.terminal}; vuelve contigo al Parking`);out.push(`↘ ${hm(t.car_depart)} · Salir hacia Parking con el vehículo`);out.push(`${hm(t.worker_end)} · Llegada prevista al Parking`)}if(t.fixed)out.push('🔒 Asignación manual preestablecida')}return out.join('\n')}
async function optimize(actor:number,body:any){const cfg=await config(),epoch=Number(body.writer_epoch);await requireWriter(actor,epoch);let route_refresh:any=null;try{route_refresh=await refreshRoutes(false)}catch(e){route_refresh={matrix_ready:false,reason:String((e as Error)?.message||e)}}const days=Math.min(Math.max(Number(body.horizon_days)||Number(cfg.default_horizon_days),1),31),start=new Date(),end=new Date(+start+days*86400000),all=await tasks(start.toISOString(),end.toISOString()),cand=await candidateWorkers(),active=await allActiveWorkers(),mx=await matrix();if(!cand.length)throw new AppError('no_active_workers');const result=buildPhysical(all,cand,active,cfg,mx),snap={manual_task_ids:all.filter((t:any)=>t.assigned_worker).map((t:any)=>t.id),task_versions:Object.fromEntries(all.map((t:any)=>[t.id,t.version])),active_worker_ids:cand.map((w:any)=>w.id),route_refresh,physical_feasible:result.physical_feasible,unmatched_needs:result.unmatched_needs,unassigned:result.unassigned,reviews:result.reviews,movement_contract_version:result.movement_contract_version,shuttle_config:{access_minutes:Number(cfg.terminal_shuttle_access_minutes),wait_day_minutes:Number(cfg.terminal_shuttle_wait_day_minutes),wait_night_minutes:Number(cfg.terminal_shuttle_wait_night_minutes),day_start_hour:Number(cfg.terminal_shuttle_day_start_hour),day_end_hour:Number(cfg.terminal_shuttle_day_end_hour)}},rec=(await insert('ai_dispatch_plans',{created_by_telegram_user_id:actor,writer_epoch:epoch,horizon_start:start.toISOString(),horizon_end:end.toISOString(),status:'proposal',solver_engine:'physical_diagnostic_v3_configurable_shuttle',input_snapshot:snap,plan:{assignments:result.assignments,fixed_task_ids:snap.manual_task_ids,physical_feasible:result.physical_feasible,unmatched_needs:result.unmatched_needs,unassigned:result.unassigned,requires_review:result.requires_review,reviews:result.reviews,movement_contract_version:result.movement_contract_version,shuttle_config:snap.shuttle_config},reports:result.reports}))[0];return{plan_id:rec.id,horizon_start:start.toISOString(),horizon_end:end.toISOString(),assignments:result.assignments,fixed_count:result.fixed_count,reports:result.reports,solver_engine:'physical_diagnostic_v3_configurable_shuttle',route_refresh,physical_feasible:result.physical_feasible,unmatched_needs:result.unmatched_needs,unassigned:result.unassigned,requires_review:result.requires_review,reviews:result.reviews,movement_contract_version:result.movement_contract_version,shuttle_config:snap.shuttle_config,confirmation_enabled:true,engine_status:'physical_model_diagnostic_v3'}}
async function confirm(actor:number,body:any){
  const planId=String(body.plan_id||'');
  if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(planId))throw new AppError('invalid_plan_id');
  return await rpc('ai_dispatch_confirm_plan',{p_actor_telegram_user_id:actor,p_plan_id:planId});
}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors()});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const o=req.headers.get('Origin');if(o&&o!==ORIGIN)throw new AppError('origin_not_allowed',403);const b=await req.json(),actor=await auth(String(b.initData||'')),action=String(b.action||'');if(action==='status'){const cfg=await config(),dash=await rpc('parking_booking_dashboard',{p_actor_telegram_user_id:actor,p_query:'',p_limit:1,p_offset:0}),ns=await nodes();return json({ok:true,permission:dash.permission,default_horizon_days:cfg.default_horizon_days,google_routes_configured:Boolean(MAPS_KEY),nodes:ns.map((n:any)=>({code:n.code,resolved:Boolean(n.place_id||(n.latitude!=null&&n.longitude!=null))})),confirmation_enabled:true,engine_status:'physical_model_diagnostic_v3',t4s_policy:'normalize_to_t4_with_review',movement_contract_version:'v2_shuttle_config',shuttle_config:{access_minutes:Number(cfg.terminal_shuttle_access_minutes),wait_day_minutes:Number(cfg.terminal_shuttle_wait_day_minutes),wait_night_minutes:Number(cfg.terminal_shuttle_wait_night_minutes),day_start_hour:Number(cfg.terminal_shuttle_day_start_hour),day_end_hour:Number(cfg.terminal_shuttle_day_end_hour)}})}if(action==='refresh_routes'){await requireWriter(actor,Number(b.writer_epoch));return json({ok:true,...await refreshRoutes(Boolean(b.force),b.required_bands,b.required_terminals)})}if(action==='optimize')return json({ok:true,...await optimize(actor,b)});if(action==='confirm')return json({ok:true,...await confirm(actor,b)});if(action==='reject'){await requireWriter(actor,Number(b.writer_epoch));await patch('ai_dispatch_plans',{id:`eq.${String(b.plan_id||'')}`,created_by_telegram_user_id:`eq.${actor}`,status:'eq.proposal'},{status:'rejected'});return json({ok:true})}throw new AppError('invalid_action')}catch(e){console.error(e);const x=e as AppError;return json({ok:false,error:String(x?.message||e)},x?.status||400)}});
