import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const BOT_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")!;
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SECRET_KEYS_JSON=Deno.env.get("SUPABASE_SECRET_KEYS");
const LEGACY_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
const ALLOW_ORIGIN="https://jdlc86.github.io";
const INIT_DATA_MAX_AGE_SECONDS=600;
function serverKey(){if(SECRET_KEYS_JSON){try{const p=JSON.parse(SECRET_KEYS_JSON);if(p?.default)return p.default;const v=Object.values(p??{})[0];if(typeof v==="string")return v}catch{}}if(LEGACY_SERVICE_ROLE_KEY)return LEGACY_SERVICE_ROLE_KEY;throw new Error("No server key")}
function cors(){return{"Access-Control-Allow-Origin":ALLOW_ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}
function json(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...cors()}})}
function eqBytes(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a[i]^b[i];return x===0}
function hexToBytes(s:string){if(!/^[0-9a-fA-F]{64}$/.test(s))return null;const out=new Uint8Array(32);for(let i=0;i<32;i++)out[i]=parseInt(s.slice(i*2,i*2+2),16);return out}
async function hmac(key:Uint8Array|string,msg:string){const kb=typeof key==="string"?new TextEncoder().encode(key):key;const k=await crypto.subtle.importKey("raw",kb,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(msg)))}
async function validateInitData(initData:string){const p=new URLSearchParams(initData),hash=p.get("hash")??"";p.delete("hash");const pairs:[string,string][]=[];for(const[k,v]of p.entries())pairs.push([k,v]);pairs.sort((a,b)=>a[0].localeCompare(b[0]));const check=pairs.map(([k,v])=>`${k}=${v}`).join("\n"),secret=await hmac("WebAppData",BOT_TOKEN),calc=await hmac(secret,check),given=hexToBytes(hash);if(!given||!eqBytes(calc,given))throw new Error("invalid_init_data");const auth=Number(p.get("auth_date")??0);if(!Number.isFinite(auth)||Math.abs(Date.now()/1000-auth)>INIT_DATA_MAX_AGE_SECONDS)throw new Error("expired_init_data");let user:any=null;try{user=JSON.parse(p.get("user")??"null")}catch{}const id=Number(user?.id);if(!Number.isFinite(id))throw new Error("missing_user");return{id}}
async function sha256AccessToken(value:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));return[...d].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function validateAccessSession(token:string){if(!token)return null;const k=serverKey();const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/validate_miniapp_access_session`,{method:"POST",headers:{apikey:k,Authorization:`Bearer ${k}`,"Content-Type":"application/json"},body:JSON.stringify({p_token_hash:await sha256AccessToken(token)})});if(!r.ok)throw new Error("access_session_validation_failed");const data=await r.json();const row=Array.isArray(data)?data[0]:data;if(!row?.telegram_user_id)throw new Error("expired_access_session");return Number(row.telegram_user_id)}
async function authenticateRequest(initData:string,token:string){const uid=await validateAccessSession(token);if(uid)return{id:uid,user:null};return validateInitData(initData)}

async function rpc(name:string,body:any){const key=serverKey();const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const raw=await r.text();let data:any=null;try{data=JSON.parse(raw)}catch{}if(!r.ok)throw new Error(data?.message||raw||"network_error");return data}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors()});if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);try{const origin=req.headers.get("Origin");if(origin&&origin!==ALLOW_ORIGIN)return json({ok:false,error:"origin_not_allowed"},403);const body=await req.json(),auth=await authenticateRequest(String(body.initData??""),String(body.access_session_token??"")),action=String(body.action??"snapshot");if(action==="snapshot"){const d=await rpc("vehicle_lifecycle_snapshot",{p_actor_telegram_user_id:auth.id});return json({ok:true,...d})}if(action==="search"){const d=await rpc("vehicle_lifecycle_search",{p_actor_telegram_user_id:auth.id,p_plate:String(body.plate??"")});return json({ok:true,...d})}return json({ok:false,error:"invalid_action"},400)}catch(e){const m=String((e as Error)?.message??e);return json({ok:false,error:m},m.includes("not_authorized")?403:400)}});
