import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const BOT_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")!;
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SECRET_KEYS_JSON=Deno.env.get("SUPABASE_SECRET_KEYS");
const LEGACY_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
const ALLOW_ORIGIN="https://jdlc86.github.io";
const APP_URL="https://jdlc86.github.io/MartinGallardo_GPS/preview-modern/?v=20260904B04";
const INIT_DATA_MAX_AGE_SECONDS=86400;
function serverKey(){if(SECRET_KEYS_JSON){try{const p=JSON.parse(SECRET_KEYS_JSON);if(p?.default)return p.default;const v=Object.values(p??{})[0];if(typeof v==="string")return v}catch{}}if(LEGACY_SERVICE_ROLE_KEY)return LEGACY_SERVICE_ROLE_KEY;throw new Error("No server key")}
function hdr(extra:Record<string,string>={}){const k=serverKey();return{apikey:k,Authorization:`Bearer ${k}`,...extra}}
function cors(){return{"Access-Control-Allow-Origin":ALLOW_ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}
function json(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...cors()}})}
function eqBytes(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a[i]^b[i];return x===0}
function hexToBytes(s:string){if(!/^[0-9a-fA-F]{64}$/.test(s))return null;const out=new Uint8Array(32);for(let i=0;i<32;i++)out[i]=parseInt(s.slice(i*2,i*2+2),16);return out}
async function hmac(key:Uint8Array|string,msg:string){const kb=typeof key==="string"?new TextEncoder().encode(key):key;const k=await crypto.subtle.importKey("raw",kb,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(msg)))}
async function validateInitData(initData:string){const p=new URLSearchParams(initData),hash=p.get("hash")??"";p.delete("hash");const pairs:[string,string][]=[];for(const[k,v]of p.entries())pairs.push([k,v]);pairs.sort((a,b)=>a[0].localeCompare(b[0]));const check=pairs.map(([k,v])=>`${k}=${v}`).join("\n"),secret=await hmac("WebAppData",BOT_TOKEN),calc=await hmac(secret,check),given=hexToBytes(hash);if(!given||!eqBytes(calc,given))throw new Error("invalid_init_data");const auth=Number(p.get("auth_date")??0);if(!Number.isFinite(auth)||Math.abs(Date.now()/1000-auth)>INIT_DATA_MAX_AGE_SECONDS)throw new Error("expired_init_data");let user:any=null;try{user=JSON.parse(p.get("user")??"null")}catch{}const id=Number(user?.id);if(!Number.isFinite(id))throw new Error("missing_user");return{id,user}}
async function request(table:string,params:Record<string,string>){const u=new URL(`${SUPABASE_URL}/rest/v1/${table}`);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);const r=await fetch(u,{headers:hdr({Accept:"application/json"})});if(!r.ok)throw new Error(await r.text());return{rows:await r.json()}}
async function one(table:string,params:Record<string,string>){return(await request(table,{...params,limit:"1"})).rows[0]??null}
async function write(method:string,table:string,filters:Record<string,string>,body:any){const u=new URL(`${SUPABASE_URL}/rest/v1/${table}`);for(const[k,v]of Object.entries(filters))u.searchParams.set(k,v);const r=await fetch(u,{method,headers:hdr({"Content-Type":"application/json",Prefer:"return=minimal"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text())}
async function insert(table:string,body:any){return write("POST",table,{},body)}
async function patch(table:string,filters:Record<string,string>,body:any){return write("PATCH",table,filters,body)}
async function currentUser(id:number){return one("telegram_users",{telegram_user_id:`eq.${id}`,select:"telegram_user_id,username,first_name,last_name,role,active,deactivated_at,created_at"})}
function nameOf(x:any){return [x?.first_name,x?.last_name].filter(Boolean).join(" ")||(x?.username?`@${x.username}`:`Usuario ${x?.telegram_user_id??""}`)}
function visibleRole(role:string){return role==="owner"?"Root":role==="admin"?"Admin":"Operario"}
async function tg(method:string,body:any){const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error(`telegram_${method}_${r.status}`)}
async function notify(user:any,type:string){try{const role=visibleRole(String(user.role)),name=nameOf(user);let text=type==="approved"?`✅ ¡Bienvenido a ParkingMartin-G, ${name}!\n\nTu solicitud ha sido aceptada.\n\n👤 Rol asignado: ${role}`:type==="reactivated"?`✅ ¡Bienvenido de nuevo, ${name}!\n\n👤 Rol: ${role}`:`👤 Tu rol ha cambiado\n\nNuevo rol: ${role}`;await tg("sendMessage",{chat_id:Number(user.telegram_user_id),text,reply_markup:{inline_keyboard:[[{text:"🚘 ABRIR PARKINGMARTIN-G",web_app:{url:APP_URL}}]]}})}catch(e){console.error(e)}}
async function requireAdmin(id:number){const u=await currentUser(id);if(!u||!u.active||(u.role!=="owner"&&u.role!=="admin"))throw new Error("not_admin");return u}
async function syncWorker(target:any){const role=target.role==="owner"||target.role==="admin"?"admin":"operator";const w=await one("workers",{telegram_user_id:`eq.${target.telegram_user_id}`,select:"id"});if(w)await patch("workers",{telegram_user_id:`eq.${target.telegram_user_id}`},{full_name:nameOf(target),role,active:target.active,deactivated_at:target.active?null:new Date().toISOString()});else if(target.active)await insert("workers",{telegram_user_id:target.telegram_user_id,full_name:nameOf(target),role,active:true})}
async function teamData(actorId:number){await requireAdmin(actorId);const pending=(await request("telegram_access_requests",{status:"eq.pending",select:"telegram_user_id,username,first_name,last_name,last_seen_at,expires_at,attempts",order:"last_seen_at.desc",limit:"50"})).rows,active=(await request("telegram_users",{active:"eq.true",select:"telegram_user_id,username,first_name,last_name,role,active,created_at",order:"created_at.asc",limit:"100"})).rows,blocked=(await request("telegram_users",{active:"eq.false",select:"telegram_user_id,username,first_name,last_name,role,active,deactivated_at",order:"deactivated_at.desc",limit:"100"})).rows;return{pending,active,blocked,stats:{active:active.length,admins:active.filter((x:any)=>x.role==="admin").length,pending:pending.length,blocked:blocked.length}}}
async function adminAction(actorId:number,targetId:number,op:string){await requireAdmin(actorId);if(targetId===actorId)throw new Error("self_change_not_allowed");const before=await currentUser(targetId);if(before?.role==="owner")throw new Error("owner_protected");if(op==="approve"||op==="approve_admin"){const req=await one("telegram_access_requests",{telegram_user_id:`eq.${targetId}`,select:"telegram_user_id,username,first_name,last_name,status"}),role=op==="approve_admin"?"admin":"operario";if(before)await patch("telegram_users",{telegram_user_id:`eq.${targetId}`},{role,active:true,deactivated_at:null});else await insert("telegram_users",{telegram_user_id:targetId,username:req?.username??null,first_name:req?.first_name??null,last_name:req?.last_name??null,role,active:true});await patch("telegram_access_requests",{telegram_user_id:`eq.${targetId}`},{status:"approved",expires_at:null});const after=await currentUser(targetId);await syncWorker(after);await notify(after,"approved");return}if(!before)throw new Error("target_not_found");if(op==="deactivate")await patch("telegram_users",{telegram_user_id:`eq.${targetId}`},{active:false,deactivated_at:new Date().toISOString()});else if(op==="reactivate")await patch("telegram_users",{telegram_user_id:`eq.${targetId}`},{active:true,deactivated_at:null});else if(op==="promote")await patch("telegram_users",{telegram_user_id:`eq.${targetId}`},{role:"admin",active:true,deactivated_at:null});else if(op==="demote")await patch("telegram_users",{telegram_user_id:`eq.${targetId}`},{role:"operario"});else if(op==="reject")await patch("telegram_access_requests",{telegram_user_id:`eq.${targetId}`},{status:"rejected",expires_at:null});else throw new Error("invalid_admin_action");const after=await currentUser(targetId);if(after){await syncWorker(after);if(op==="reactivate"||op==="promote"||op==="demote")await notify(after,op==="reactivate"?"reactivated":"role")}}
async function vehiclesData(){return(await request("vehicles",{select:"id,plate,normalized_plate,status,parked_at,updated_at,current_lat,current_lng,current_accuracy_m,current_location_text",order:"updated_at.desc",limit:"100"})).rows}
async function recentData(){const events=(await request("parking_events",{select:"id,vehicle_id,worker_id,operation,location_text,gps_quality,created_at,metadata",order:"created_at.desc",limit:"80"})).rows;const vehicleIds=[...new Set(events.map((x:any)=>x.vehicle_id).filter(Boolean))],workerIds=[...new Set(events.map((x:any)=>x.worker_id).filter(Boolean))];let vehicles:any[]=[],workers:any[]=[];if(vehicleIds.length)vehicles=(await request("vehicles",{id:`in.(${vehicleIds.join(",")})`,select:"id,plate,status"})).rows;if(workerIds.length)workers=(await request("workers",{id:`in.(${workerIds.join(",")})`,select:"id,full_name,role"})).rows;const vm=Object.fromEntries(vehicles.map((v:any)=>[v.id,v])),wm=Object.fromEntries(workers.map((w:any)=>[w.id,w]));return events.map((e:any)=>({...e,vehicle:e.vehicle_id?vm[e.vehicle_id]??null:null,worker:e.worker_id?wm[e.worker_id]??null:null}))}
const madridFmt=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Madrid",year:"numeric",month:"2-digit",day:"2-digit"});
async function workerDailyStats(telegramUserId:number){const worker=await one("workers",{telegram_user_id:`eq.${telegramUserId}`,select:"id"});if(!worker)return{picked_up:0,parked:0,relocated:0,delivered:0};const day=madridFmt.format(new Date()),events=(await request("parking_events",{worker_id:`eq.${worker.id}`,operation:"in.(pickup,park,relocate,retrieve)",select:"operation,created_at",order:"created_at.desc",limit:"1000"})).rows.filter((e:any)=>madridFmt.format(new Date(e.created_at))===day);return{picked_up:events.filter((e:any)=>e.operation==="pickup").length,parked:events.filter((e:any)=>e.operation==="park").length,relocated:events.filter((e:any)=>e.operation==="relocate").length,delivered:events.filter((e:any)=>e.operation==="retrieve").length}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors()});if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);try{const origin=req.headers.get("Origin");if(origin&&origin!==ALLOW_ORIGIN)return json({ok:false,error:"origin_not_allowed"},403);const body=await req.json(),auth=await validateInitData(String(body.initData??"")),user=await one("telegram_users",{telegram_user_id:`eq.${auth.id}`,active:"eq.true",select:"telegram_user_id,role,active"});if(!user)return json({ok:false,error:"not_authorized"},403);const action=String(body.action??"");if(action==="dashboard")return json({ok:true,role:user.role,stats:await workerDailyStats(auth.id)});if(action==="vehicles_dashboard")return json({ok:true,role:user.role,vehicles:await vehiclesData()});if(action==="recent_activity")return json({ok:true,role:user.role,events:await recentData()});if(action==="team_dashboard")return json({ok:true,role:user.role,...await teamData(auth.id)});if(action==="admin_action"){const targetId=Number(body.target_id),op=String(body.admin_action??"");if(!Number.isFinite(targetId))return json({ok:false,error:"invalid_target"},400);await adminAction(auth.id,targetId,op);return json({ok:true,...await teamData(auth.id)})}return json({ok:false,error:"invalid_action"},400)}catch(e){console.error(e);const m=String((e as Error)?.message??e);return json({ok:false,error:m},m==="not_admin"?403:400)}});
