create table public.parking_booking_import_analyses (
  id uuid primary key default gen_random_uuid(),
  created_by_telegram_user_id bigint not null references public.telegram_users(telegram_user_id),
  file_name text not null,
  file_sha256 text not null check (file_sha256 ~ '^[0-9a-f]{64}$'),
  ai_provider text not null,
  ai_model text not null,
  valid_rows jsonb not null default '[]'::jsonb check (jsonb_typeof(valid_rows) = 'array'),
  invalid_rows jsonb not null default '[]'::jsonb check (jsonb_typeof(invalid_rows) = 'array'),
  warnings jsonb not null default '[]'::jsonb check (jsonb_typeof(warnings) = 'array'),
  expires_at timestamptz not null default (now() + interval '2 hours'),
  committed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.parking_booking_import_batches (
  id uuid primary key default gen_random_uuid(),
  analysis_id uuid not null unique references public.parking_booking_import_analyses(id),
  file_name text not null,
  file_sha256 text not null unique check (file_sha256 ~ '^[0-9a-f]{64}$'),
  ai_provider text not null,
  ai_model text not null,
  total_rows integer not null check (total_rows >= 0),
  imported_rows integer not null check (imported_rows >= 0),
  created_by_telegram_user_id bigint not null references public.telegram_users(telegram_user_id),
  created_at timestamptz not null default now()
);

create table public.parking_bookings (
  id uuid primary key default gen_random_uuid(),
  pickup_date date not null,
  pickup_time time without time zone not null,
  pickup_terminal text not null check (char_length(pickup_terminal) between 1 and 120),
  return_date date not null,
  return_time time without time zone not null,
  return_terminal text not null check (char_length(return_terminal) between 1 and 120),
  price_eur numeric(10,2) not null check (price_eur >= 0),
  customer_name text not null check (char_length(customer_name) between 1 and 180),
  customer_email text,
  customer_phone text,
  vehicle_plate text not null check (char_length(vehicle_plate) between 2 and 24),
  vehicle_plate_normalized text generated always as (upper(regexp_replace(vehicle_plate, '[^[:alnum:]]'::text, ''::text, 'g'::text))) stored,
  vehicle_make_model text,
  payment_method text not null check (payment_method in ('cash', 'credit_card')),
  source_type text not null default 'manual' check (source_type in ('manual', 'ai_import')),
  import_batch_id uuid references public.parking_booking_import_batches(id),
  source_row integer,
  version bigint not null default 1 check (version > 0),
  created_by_telegram_user_id bigint not null references public.telegram_users(telegram_user_id),
  updated_by_telegram_user_id bigint not null references public.telegram_users(telegram_user_id),
  deleted_by_telegram_user_id bigint references public.telegram_users(telegram_user_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  check (return_date >= pickup_date),
  check ((source_type = 'manual' and import_batch_id is null) or (source_type = 'ai_import' and import_batch_id is not null))
);

create table public.parking_booking_write_state (
  id smallint primary key default 1 check (id = 1),
  holder_telegram_user_id bigint references public.telegram_users(telegram_user_id),
  epoch bigint not null default 1 check (epoch > 0),
  granted_by_telegram_user_id bigint references public.telegram_users(telegram_user_id),
  granted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.parking_booking_permission_requests (
  id uuid primary key default gen_random_uuid(),
  request_kind text not null check (request_kind in ('request', 'transfer')),
  requester_telegram_user_id bigint not null references public.telegram_users(telegram_user_id),
  recipient_telegram_user_id bigint not null references public.telegram_users(telegram_user_id),
  proposed_holder_telegram_user_id bigint not null references public.telegram_users(telegram_user_id),
  holder_at_creation_telegram_user_id bigint references public.telegram_users(telegram_user_id),
  writer_epoch bigint not null check (writer_epoch > 0),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'expired', 'cancelled')),
  responded_by_telegram_user_id bigint references public.telegram_users(telegram_user_id),
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '72 hours')
);

create table public.parking_booking_notifications (
  id bigint generated by default as identity primary key,
  recipient_telegram_user_id bigint not null references public.telegram_users(telegram_user_id),
  notification_type text not null,
  title text not null,
  body text not null,
  permission_request_id uuid references public.parking_booking_permission_requests(id),
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  telegram_claimed_at timestamptz,
  telegram_sent_at timestamptz,
  telegram_attempts integer not null default 0,
  telegram_error text,
  created_at timestamptz not null default now()
);

create table public.parking_booking_admin_events (
  id bigint generated by default as identity primary key,
  actor_telegram_user_id bigint references public.telegram_users(telegram_user_id),
  action text not null,
  entity_type text not null,
  entity_id text,
  permission_request_id uuid references public.parking_booking_permission_requests(id),
  before_data jsonb,
  after_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.parking_booking_command_dedup (
  idempotency_key uuid primary key,
  actor_telegram_user_id bigint not null references public.telegram_users(telegram_user_id),
  action text not null,
  response jsonb not null,
  created_at timestamptz not null default now()
);

create index parking_bookings_active_pickup_idx on public.parking_bookings(pickup_date, pickup_time) where deleted_at is null;
create index parking_bookings_active_plate_idx on public.parking_bookings(vehicle_plate_normalized) where deleted_at is null;
create index parking_bookings_active_customer_idx on public.parking_bookings(lower(customer_name)) where deleted_at is null;
create index parking_booking_notifications_unread_idx on public.parking_booking_notifications(recipient_telegram_user_id, created_at desc) where read_at is null;
create index parking_booking_notifications_telegram_idx on public.parking_booking_notifications(created_at) where telegram_sent_at is null;
create index parking_booking_requests_recipient_idx on public.parking_booking_permission_requests(recipient_telegram_user_id, created_at desc) where status = 'pending';
create index parking_booking_requests_requester_idx on public.parking_booking_permission_requests(requester_telegram_user_id, created_at desc) where status = 'pending';
create unique index parking_booking_requests_no_duplicate_pending_idx
  on public.parking_booking_permission_requests(request_kind, requester_telegram_user_id, recipient_telegram_user_id, proposed_holder_telegram_user_id)
  where status = 'pending';

alter table public.parking_booking_import_analyses enable row level security;
alter table public.parking_booking_import_batches enable row level security;
alter table public.parking_bookings enable row level security;
alter table public.parking_booking_write_state enable row level security;
alter table public.parking_booking_permission_requests enable row level security;
alter table public.parking_booking_notifications enable row level security;
alter table public.parking_booking_admin_events enable row level security;
alter table public.parking_booking_command_dedup enable row level security;

revoke all on table public.parking_booking_import_analyses from anon, authenticated;
revoke all on table public.parking_booking_import_batches from anon, authenticated;
revoke all on table public.parking_bookings from anon, authenticated;
revoke all on table public.parking_booking_write_state from anon, authenticated;
revoke all on table public.parking_booking_permission_requests from anon, authenticated;
revoke all on table public.parking_booking_notifications from anon, authenticated;
revoke all on table public.parking_booking_admin_events from anon, authenticated;
revoke all on table public.parking_booking_command_dedup from anon, authenticated;

grant all on table public.parking_booking_import_analyses to service_role;
grant all on table public.parking_booking_import_batches to service_role;
grant all on table public.parking_bookings to service_role;
grant all on table public.parking_booking_write_state to service_role;
grant all on table public.parking_booking_permission_requests to service_role;
grant all on table public.parking_booking_notifications to service_role;
grant all on table public.parking_booking_admin_events to service_role;
grant all on table public.parking_booking_command_dedup to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.parking_booking_write_state(holder_telegram_user_id, granted_by_telegram_user_id)
select telegram_user_id, telegram_user_id
from public.telegram_users
where active = true and role = 'owner'
order by created_at
limit 1
on conflict (id) do nothing;

create or replace function public.parking_booking_require_admin(p_actor_telegram_user_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.telegram_users
    where telegram_user_id = p_actor_telegram_user_id
      and active = true
      and role in ('owner', 'admin')
  ) then
    raise exception using errcode = '42501', message = 'not_admin';
  end if;
end;
$$;

create or replace function public.parking_booking_require_writer(p_actor_telegram_user_id bigint, p_writer_epoch bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_state public.parking_booking_write_state%rowtype;
begin
  perform public.parking_booking_require_admin(p_actor_telegram_user_id);
  select * into v_state
  from public.parking_booking_write_state
  where id = 1
  for update;
  if v_state.holder_telegram_user_id is distinct from p_actor_telegram_user_id then
    raise exception using errcode = '42501', message = 'write_permission_required';
  end if;
  if v_state.epoch is distinct from p_writer_epoch then
    raise exception using errcode = '40001', message = 'write_permission_changed';
  end if;
end;
$$;

create or replace function public.parking_booking_normalize_entry(p_entry jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_pickup_date date;
  v_pickup_time time without time zone;
  v_return_date date;
  v_return_time time without time zone;
  v_pickup_terminal text;
  v_return_terminal text;
  v_customer_name text;
  v_customer_email text;
  v_customer_phone text;
  v_vehicle_plate text;
  v_vehicle_make_model text;
  v_payment text;
  v_price_text text;
  v_price numeric(10,2);
begin
  if p_entry is null or jsonb_typeof(p_entry) <> 'object' then
    raise exception using errcode = '22023', message = 'invalid_booking_entry';
  end if;

  v_pickup_date := nullif(trim(p_entry ->> 'pickup_date'), '')::date;
  v_pickup_time := nullif(trim(p_entry ->> 'pickup_time'), '')::time;
  v_return_date := nullif(trim(p_entry ->> 'return_date'), '')::date;
  v_return_time := nullif(trim(p_entry ->> 'return_time'), '')::time;
  v_pickup_terminal := nullif(trim(p_entry ->> 'pickup_terminal'), '');
  v_return_terminal := nullif(trim(p_entry ->> 'return_terminal'), '');
  v_customer_name := nullif(trim(p_entry ->> 'customer_name'), '');
  v_customer_email := nullif(lower(trim(p_entry ->> 'customer_email')), '');
  v_customer_phone := nullif(trim(p_entry ->> 'customer_phone'), '');
  v_vehicle_plate := nullif(upper(trim(p_entry ->> 'vehicle_plate')), '');
  v_vehicle_make_model := nullif(trim(p_entry ->> 'vehicle_make_model'), '');
  v_payment := lower(trim(coalesce(p_entry ->> 'payment_method', '')));
  v_price_text := regexp_replace(coalesce(p_entry ->> 'price_eur', ''), '[€[:space:]]', '', 'g');
  if position(',' in v_price_text) > 0 and position('.' in v_price_text) > 0 then
    v_price_text := replace(replace(v_price_text, '.', ''), ',', '.');
  else
    v_price_text := replace(v_price_text, ',', '.');
  end if;
  v_price := nullif(v_price_text, '')::numeric(10,2);

  if v_payment in ('efectivo', 'cash') then v_payment := 'cash'; end if;
  if v_payment in ('tarjeta', 'tarjeta de credito', 'tarjeta de crédito', 'credito', 'crédito', 'card', 'credit_card') then v_payment := 'credit_card'; end if;

  if v_pickup_date is null or v_pickup_time is null or v_return_date is null or v_return_time is null
     or v_pickup_terminal is null or v_return_terminal is null or v_customer_name is null
     or v_vehicle_plate is null or v_price is null or v_payment not in ('cash', 'credit_card') then
    raise exception using errcode = '22023', message = 'invalid_booking_entry';
  end if;
  if v_return_date < v_pickup_date then
    raise exception using errcode = '22023', message = 'invalid_booking_dates';
  end if;
  if v_price < 0 then
    raise exception using errcode = '22023', message = 'invalid_booking_price';
  end if;
  if char_length(v_pickup_terminal) > 120 or char_length(v_return_terminal) > 120
     or char_length(v_customer_name) > 180 or char_length(v_vehicle_plate) > 24
     or char_length(coalesce(v_vehicle_make_model, '')) > 180
     or char_length(coalesce(v_customer_phone, '')) > 80
     or char_length(coalesce(v_customer_email, '')) > 254 then
    raise exception using errcode = '22023', message = 'booking_value_too_long';
  end if;
  if v_customer_email is not null and v_customer_email !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception using errcode = '22023', message = 'invalid_booking_email';
  end if;

  return jsonb_build_object(
    'pickup_date', to_char(v_pickup_date, 'YYYY-MM-DD'),
    'pickup_time', to_char(v_pickup_time, 'HH24:MI'),
    'pickup_terminal', v_pickup_terminal,
    'return_date', to_char(v_return_date, 'YYYY-MM-DD'),
    'return_time', to_char(v_return_time, 'HH24:MI'),
    'return_terminal', v_return_terminal,
    'price_eur', v_price,
    'customer_name', v_customer_name,
    'customer_email', v_customer_email,
    'customer_phone', v_customer_phone,
    'vehicle_plate', v_vehicle_plate,
    'vehicle_make_model', v_vehicle_make_model,
    'payment_method', v_payment,
    'source_row', case when coalesce(p_entry ->> 'source_row', '') ~ '^[0-9]+$' then (p_entry ->> 'source_row')::integer else null end
  );
exception
  when invalid_text_representation or datetime_field_overflow or numeric_value_out_of_range then
    raise exception using errcode = '22023', message = 'invalid_booking_entry';
end;
$$;

create or replace function public.parking_booking_dashboard(
  p_actor_telegram_user_id bigint,
  p_query text,
  p_limit integer,
  p_offset integer
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_query text := trim(coalesce(p_query, ''));
  v_limit integer := least(greatest(coalesce(p_limit, 50), 1), 200);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_result jsonb;
begin
  perform public.parking_booking_require_admin(p_actor_telegram_user_id);

  select jsonb_build_object(
    'me', (
      select jsonb_build_object(
        'telegram_user_id', u.telegram_user_id,
        'role', u.role,
        'name', coalesce(nullif(trim(concat_ws(' ', u.first_name, u.last_name)), ''), case when u.username is not null then '@' || u.username else 'Usuario ' || u.telegram_user_id::text end)
      )
      from public.telegram_users u
      where u.telegram_user_id = p_actor_telegram_user_id
    ),
    'permission', (
      select jsonb_build_object(
        'holder_telegram_user_id', s.holder_telegram_user_id,
        'holder_name', coalesce(nullif(trim(concat_ws(' ', h.first_name, h.last_name)), ''), case when h.username is not null then '@' || h.username else 'Sin titular' end),
        'epoch', s.epoch,
        'can_write', s.holder_telegram_user_id = p_actor_telegram_user_id,
        'granted_at', s.granted_at
      )
      from public.parking_booking_write_state s
      left join public.telegram_users h on h.telegram_user_id = s.holder_telegram_user_id
      where s.id = 1
    ),
    'admins', (
      select coalesce(jsonb_agg(to_jsonb(a) order by a.is_root desc, a.name), '[]'::jsonb)
      from (
        select u.telegram_user_id,
               u.role,
               (u.role = 'owner') as is_root,
               coalesce(nullif(trim(concat_ws(' ', u.first_name, u.last_name)), ''), case when u.username is not null then '@' || u.username else 'Usuario ' || u.telegram_user_id::text end) as name
        from public.telegram_users u
        where u.active = true and u.role in ('owner', 'admin')
      ) a
    ),
    'reservations', (
      select coalesce(jsonb_agg(to_jsonb(r) order by r.pickup_date, r.pickup_time, r.created_at), '[]'::jsonb)
      from (
        select b.id, b.pickup_date, b.pickup_time, b.pickup_terminal,
               b.return_date, b.return_time, b.return_terminal, b.price_eur,
               b.customer_name, b.customer_email, b.customer_phone,
               b.vehicle_plate, b.vehicle_plate_normalized, b.vehicle_make_model,
               b.payment_method, b.source_type, b.source_row, b.version,
               b.created_at, b.updated_at
        from public.parking_bookings b
        where b.deleted_at is null
          and (
            v_query = ''
            or b.customer_name ilike '%' || v_query || '%'
            or coalesce(b.customer_email, '') ilike '%' || v_query || '%'
            or coalesce(b.customer_phone, '') ilike '%' || v_query || '%'
            or b.vehicle_plate ilike '%' || v_query || '%'
            or b.vehicle_plate_normalized ilike '%' || upper(regexp_replace(v_query, '[^[:alnum:]]', '', 'g')) || '%'
            or coalesce(b.vehicle_make_model, '') ilike '%' || v_query || '%'
            or b.pickup_terminal ilike '%' || v_query || '%'
            or b.return_terminal ilike '%' || v_query || '%'
            or to_char(b.pickup_date, 'DD/MM/YYYY') ilike '%' || v_query || '%'
            or to_char(b.return_date, 'DD/MM/YYYY') ilike '%' || v_query || '%'
          )
        order by b.pickup_date, b.pickup_time, b.created_at
        limit v_limit offset v_offset
      ) r
    ),
    'total', (
      select count(*)
      from public.parking_bookings b
      where b.deleted_at is null
        and (
          v_query = ''
          or b.customer_name ilike '%' || v_query || '%'
          or coalesce(b.customer_email, '') ilike '%' || v_query || '%'
          or coalesce(b.customer_phone, '') ilike '%' || v_query || '%'
          or b.vehicle_plate ilike '%' || v_query || '%'
          or b.vehicle_plate_normalized ilike '%' || upper(regexp_replace(v_query, '[^[:alnum:]]', '', 'g')) || '%'
          or coalesce(b.vehicle_make_model, '') ilike '%' || v_query || '%'
          or b.pickup_terminal ilike '%' || v_query || '%'
          or b.return_terminal ilike '%' || v_query || '%'
          or to_char(b.pickup_date, 'DD/MM/YYYY') ilike '%' || v_query || '%'
          or to_char(b.return_date, 'DD/MM/YYYY') ilike '%' || v_query || '%'
        )
    ),
    'stats', (
      select jsonb_build_object(
        'active', count(*) filter (where deleted_at is null),
        'today', count(*) filter (where deleted_at is null and pickup_date = current_date),
        'upcoming', count(*) filter (where deleted_at is null and pickup_date > current_date),
        'imported', count(*) filter (where deleted_at is null and source_type = 'ai_import')
      )
      from public.parking_bookings
    ),
    'notifications', (
      select coalesce(jsonb_agg(to_jsonb(n) order by n.created_at desc), '[]'::jsonb)
      from (
        select id, notification_type, title, body, permission_request_id, payload, read_at, created_at
        from public.parking_booking_notifications
        where recipient_telegram_user_id = p_actor_telegram_user_id
        order by created_at desc
        limit 50
      ) n
    ),
    'unread_count', (
      select count(*) from public.parking_booking_notifications
      where recipient_telegram_user_id = p_actor_telegram_user_id and read_at is null
    ),
    'pending_requests', (
      select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at), '[]'::jsonb)
      from (
        select pr.id, pr.request_kind, pr.requester_telegram_user_id,
               pr.proposed_holder_telegram_user_id, pr.writer_epoch, pr.created_at, pr.expires_at,
               coalesce(nullif(trim(concat_ws(' ', rq.first_name, rq.last_name)), ''), case when rq.username is not null then '@' || rq.username else 'Usuario ' || rq.telegram_user_id::text end) as requester_name,
               coalesce(nullif(trim(concat_ws(' ', ph.first_name, ph.last_name)), ''), case when ph.username is not null then '@' || ph.username else 'Usuario ' || ph.telegram_user_id::text end) as proposed_holder_name
        from public.parking_booking_permission_requests pr
        join public.telegram_users rq on rq.telegram_user_id = pr.requester_telegram_user_id
        join public.telegram_users ph on ph.telegram_user_id = pr.proposed_holder_telegram_user_id
        where pr.recipient_telegram_user_id = p_actor_telegram_user_id
          and pr.status = 'pending'
          and pr.expires_at > now()
      ) x
    ),
    'outgoing_requests', (
      select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at), '[]'::jsonb)
      from (
        select pr.id, pr.request_kind, pr.recipient_telegram_user_id,
               pr.proposed_holder_telegram_user_id, pr.created_at, pr.expires_at,
               coalesce(nullif(trim(concat_ws(' ', rc.first_name, rc.last_name)), ''), case when rc.username is not null then '@' || rc.username else 'Usuario ' || rc.telegram_user_id::text end) as recipient_name
        from public.parking_booking_permission_requests pr
        join public.telegram_users rc on rc.telegram_user_id = pr.recipient_telegram_user_id
        where pr.requester_telegram_user_id = p_actor_telegram_user_id
          and pr.status = 'pending'
          and pr.expires_at > now()
      ) x
    )
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.parking_booking_create(
  p_actor_telegram_user_id bigint,
  p_writer_epoch bigint,
  p_idempotency_key uuid,
  p_entry jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_existing public.parking_booking_command_dedup%rowtype;
  v_norm jsonb;
  v_row public.parking_bookings%rowtype;
  v_response jsonb;
begin
  select * into v_existing from public.parking_booking_command_dedup where idempotency_key = p_idempotency_key;
  if found then
    if v_existing.actor_telegram_user_id <> p_actor_telegram_user_id or v_existing.action <> 'create' then
      raise exception using errcode = '22023', message = 'idempotency_key_reused';
    end if;
    return v_existing.response;
  end if;

  perform public.parking_booking_require_writer(p_actor_telegram_user_id, p_writer_epoch);
  v_norm := public.parking_booking_normalize_entry(p_entry);

  insert into public.parking_bookings(
    pickup_date, pickup_time, pickup_terminal, return_date, return_time, return_terminal,
    price_eur, customer_name, customer_email, customer_phone, vehicle_plate,
    vehicle_make_model, payment_method, source_type,
    created_by_telegram_user_id, updated_by_telegram_user_id
  ) values (
    (v_norm ->> 'pickup_date')::date, (v_norm ->> 'pickup_time')::time, v_norm ->> 'pickup_terminal',
    (v_norm ->> 'return_date')::date, (v_norm ->> 'return_time')::time, v_norm ->> 'return_terminal',
    (v_norm ->> 'price_eur')::numeric, v_norm ->> 'customer_name', nullif(v_norm ->> 'customer_email', ''),
    nullif(v_norm ->> 'customer_phone', ''), v_norm ->> 'vehicle_plate', nullif(v_norm ->> 'vehicle_make_model', ''),
    v_norm ->> 'payment_method', 'manual', p_actor_telegram_user_id, p_actor_telegram_user_id
  ) returning * into v_row;

  insert into public.parking_booking_admin_events(actor_telegram_user_id, action, entity_type, entity_id, after_data)
  values (p_actor_telegram_user_id, 'create', 'booking', v_row.id::text, to_jsonb(v_row));

  v_response := jsonb_build_object('booking', to_jsonb(v_row));
  insert into public.parking_booking_command_dedup(idempotency_key, actor_telegram_user_id, action, response)
  values (p_idempotency_key, p_actor_telegram_user_id, 'create', v_response);
  return v_response;
end;
$$;

create or replace function public.parking_booking_update(
  p_actor_telegram_user_id bigint,
  p_writer_epoch bigint,
  p_idempotency_key uuid,
  p_booking_id uuid,
  p_expected_version bigint,
  p_entry jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_existing public.parking_booking_command_dedup%rowtype;
  v_norm jsonb;
  v_before public.parking_bookings%rowtype;
  v_after public.parking_bookings%rowtype;
  v_response jsonb;
begin
  select * into v_existing from public.parking_booking_command_dedup where idempotency_key = p_idempotency_key;
  if found then
    if v_existing.actor_telegram_user_id <> p_actor_telegram_user_id or v_existing.action <> 'update' then
      raise exception using errcode = '22023', message = 'idempotency_key_reused';
    end if;
    return v_existing.response;
  end if;

  perform public.parking_booking_require_writer(p_actor_telegram_user_id, p_writer_epoch);
  select * into v_before from public.parking_bookings where id = p_booking_id and deleted_at is null for update;
  if not found then raise exception using errcode = 'P0002', message = 'booking_not_found'; end if;
  if v_before.version <> p_expected_version then raise exception using errcode = '40001', message = 'booking_conflict'; end if;
  v_norm := public.parking_booking_normalize_entry(p_entry);

  update public.parking_bookings set
    pickup_date = (v_norm ->> 'pickup_date')::date,
    pickup_time = (v_norm ->> 'pickup_time')::time,
    pickup_terminal = v_norm ->> 'pickup_terminal',
    return_date = (v_norm ->> 'return_date')::date,
    return_time = (v_norm ->> 'return_time')::time,
    return_terminal = v_norm ->> 'return_terminal',
    price_eur = (v_norm ->> 'price_eur')::numeric,
    customer_name = v_norm ->> 'customer_name',
    customer_email = nullif(v_norm ->> 'customer_email', ''),
    customer_phone = nullif(v_norm ->> 'customer_phone', ''),
    vehicle_plate = v_norm ->> 'vehicle_plate',
    vehicle_make_model = nullif(v_norm ->> 'vehicle_make_model', ''),
    payment_method = v_norm ->> 'payment_method',
    version = version + 1,
    updated_by_telegram_user_id = p_actor_telegram_user_id,
    updated_at = now()
  where id = p_booking_id
  returning * into v_after;

  insert into public.parking_booking_admin_events(actor_telegram_user_id, action, entity_type, entity_id, before_data, after_data)
  values (p_actor_telegram_user_id, 'update', 'booking', p_booking_id::text, to_jsonb(v_before), to_jsonb(v_after));

  v_response := jsonb_build_object('booking', to_jsonb(v_after));
  insert into public.parking_booking_command_dedup(idempotency_key, actor_telegram_user_id, action, response)
  values (p_idempotency_key, p_actor_telegram_user_id, 'update', v_response);
  return v_response;
end;
$$;

create or replace function public.parking_booking_delete_many(
  p_actor_telegram_user_id bigint,
  p_writer_epoch bigint,
  p_idempotency_key uuid,
  p_items jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_existing public.parking_booking_command_dedup%rowtype;
  v_item jsonb;
  v_row public.parking_bookings%rowtype;
  v_ids uuid[] := '{}'::uuid[];
  v_before jsonb := '[]'::jsonb;
  v_id uuid;
  v_version bigint;
  v_response jsonb;
begin
  select * into v_existing from public.parking_booking_command_dedup where idempotency_key = p_idempotency_key;
  if found then
    if v_existing.actor_telegram_user_id <> p_actor_telegram_user_id or v_existing.action <> 'delete_many' then
      raise exception using errcode = '22023', message = 'idempotency_key_reused';
    end if;
    return v_existing.response;
  end if;

  perform public.parking_booking_require_writer(p_actor_telegram_user_id, p_writer_epoch);
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 200 then
    raise exception using errcode = '22023', message = 'invalid_bulk_selection';
  end if;

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_id := (v_item ->> 'id')::uuid;
    v_version := (v_item ->> 'version')::bigint;
    if v_id = any(v_ids) then raise exception using errcode = '22023', message = 'duplicate_bulk_selection'; end if;
    select * into v_row from public.parking_bookings where id = v_id and deleted_at is null for update;
    if not found then raise exception using errcode = 'P0002', message = 'booking_not_found'; end if;
    if v_row.version <> v_version then raise exception using errcode = '40001', message = 'booking_conflict'; end if;
    v_ids := array_append(v_ids, v_id);
    v_before := v_before || jsonb_build_array(to_jsonb(v_row));
  end loop;

  update public.parking_bookings set
    deleted_at = now(),
    deleted_by_telegram_user_id = p_actor_telegram_user_id,
    updated_by_telegram_user_id = p_actor_telegram_user_id,
    updated_at = now(),
    version = version + 1
  where id = any(v_ids);

  insert into public.parking_booking_admin_events(actor_telegram_user_id, action, entity_type, before_data, metadata)
  values (p_actor_telegram_user_id, 'delete_many', 'booking', v_before, jsonb_build_object('ids', to_jsonb(v_ids), 'count', cardinality(v_ids)));

  v_response := jsonb_build_object('deleted_ids', to_jsonb(v_ids), 'count', cardinality(v_ids));
  insert into public.parking_booking_command_dedup(idempotency_key, actor_telegram_user_id, action, response)
  values (p_idempotency_key, p_actor_telegram_user_id, 'delete_many', v_response);
  return v_response;
exception
  when invalid_text_representation then
    raise exception using errcode = '22023', message = 'invalid_bulk_selection';
end;
$$;

create or replace function public.parking_booking_import_commit(
  p_actor_telegram_user_id bigint,
  p_writer_epoch bigint,
  p_idempotency_key uuid,
  p_analysis_id uuid,
  p_selected_source_rows jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_existing public.parking_booking_command_dedup%rowtype;
  v_analysis public.parking_booking_import_analyses%rowtype;
  v_existing_batch public.parking_booking_import_batches%rowtype;
  v_batch public.parking_booking_import_batches%rowtype;
  v_entry jsonb;
  v_norm jsonb;
  v_selected integer[] := '{}'::integer[];
  v_selected_value jsonb;
  v_source_row integer;
  v_imported integer := 0;
  v_ids jsonb := '[]'::jsonb;
  v_row public.parking_bookings%rowtype;
  v_response jsonb;
begin
  select * into v_existing from public.parking_booking_command_dedup where idempotency_key = p_idempotency_key;
  if found then
    if v_existing.actor_telegram_user_id <> p_actor_telegram_user_id or v_existing.action <> 'import_commit' then
      raise exception using errcode = '22023', message = 'idempotency_key_reused';
    end if;
    return v_existing.response;
  end if;

  perform public.parking_booking_require_writer(p_actor_telegram_user_id, p_writer_epoch);
  select * into v_analysis
  from public.parking_booking_import_analyses
  where id = p_analysis_id and created_by_telegram_user_id = p_actor_telegram_user_id
  for update;
  if not found then raise exception using errcode = 'P0002', message = 'import_analysis_not_found'; end if;
  if v_analysis.expires_at <= now() then raise exception using errcode = '22023', message = 'import_analysis_expired'; end if;

  select * into v_existing_batch from public.parking_booking_import_batches where file_sha256 = v_analysis.file_sha256;
  if found then
    v_response := jsonb_build_object('duplicate', true, 'batch_id', v_existing_batch.id, 'count', v_existing_batch.imported_rows);
    insert into public.parking_booking_command_dedup(idempotency_key, actor_telegram_user_id, action, response)
    values (p_idempotency_key, p_actor_telegram_user_id, 'import_commit', v_response);
    return v_response;
  end if;

  if p_selected_source_rows is not null then
    if jsonb_typeof(p_selected_source_rows) <> 'array' then raise exception using errcode = '22023', message = 'invalid_import_selection'; end if;
    for v_selected_value in select value from jsonb_array_elements(p_selected_source_rows) loop
      v_source_row := (v_selected_value #>> '{}')::integer;
      if v_source_row = any(v_selected) then raise exception using errcode = '22023', message = 'invalid_import_selection'; end if;
      v_selected := array_append(v_selected, v_source_row);
    end loop;
  end if;

  insert into public.parking_booking_import_batches(
    analysis_id, file_name, file_sha256, ai_provider, ai_model,
    total_rows, imported_rows, created_by_telegram_user_id
  ) values (
    v_analysis.id, v_analysis.file_name, v_analysis.file_sha256, v_analysis.ai_provider, v_analysis.ai_model,
    jsonb_array_length(v_analysis.valid_rows), 0, p_actor_telegram_user_id
  ) returning * into v_batch;

  for v_entry in select value from jsonb_array_elements(v_analysis.valid_rows) loop
    v_source_row := nullif(v_entry ->> 'source_row', '')::integer;
    if cardinality(v_selected) > 0 and not (v_source_row = any(v_selected)) then continue; end if;
    v_norm := public.parking_booking_normalize_entry(v_entry);
    insert into public.parking_bookings(
      pickup_date, pickup_time, pickup_terminal, return_date, return_time, return_terminal,
      price_eur, customer_name, customer_email, customer_phone, vehicle_plate,
      vehicle_make_model, payment_method, source_type, import_batch_id, source_row,
      created_by_telegram_user_id, updated_by_telegram_user_id
    ) values (
      (v_norm ->> 'pickup_date')::date, (v_norm ->> 'pickup_time')::time, v_norm ->> 'pickup_terminal',
      (v_norm ->> 'return_date')::date, (v_norm ->> 'return_time')::time, v_norm ->> 'return_terminal',
      (v_norm ->> 'price_eur')::numeric, v_norm ->> 'customer_name', nullif(v_norm ->> 'customer_email', ''),
      nullif(v_norm ->> 'customer_phone', ''), v_norm ->> 'vehicle_plate', nullif(v_norm ->> 'vehicle_make_model', ''),
      v_norm ->> 'payment_method', 'ai_import', v_batch.id, v_source_row,
      p_actor_telegram_user_id, p_actor_telegram_user_id
    ) returning * into v_row;
    v_imported := v_imported + 1;
    v_ids := v_ids || jsonb_build_array(v_row.id);
  end loop;

  if v_imported < 1 then raise exception using errcode = '22023', message = 'empty_import_selection'; end if;
  update public.parking_booking_import_batches set imported_rows = v_imported where id = v_batch.id;
  update public.parking_booking_import_analyses set committed_at = now() where id = v_analysis.id;
  insert into public.parking_booking_admin_events(actor_telegram_user_id, action, entity_type, entity_id, metadata)
  values (p_actor_telegram_user_id, 'import_commit', 'import_batch', v_batch.id::text,
          jsonb_build_object('analysis_id', v_analysis.id, 'file_name', v_analysis.file_name, 'count', v_imported, 'booking_ids', v_ids, 'ai_model', v_analysis.ai_model));

  v_response := jsonb_build_object('duplicate', false, 'batch_id', v_batch.id, 'count', v_imported, 'booking_ids', v_ids);
  insert into public.parking_booking_command_dedup(idempotency_key, actor_telegram_user_id, action, response)
  values (p_idempotency_key, p_actor_telegram_user_id, 'import_commit', v_response);
  return v_response;
exception
  when invalid_text_representation then
    raise exception using errcode = '22023', message = 'invalid_import_selection';
end;
$$;

create or replace function public.parking_booking_request_write(
  p_actor_telegram_user_id bigint,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_existing public.parking_booking_command_dedup%rowtype;
  v_state public.parking_booking_write_state%rowtype;
  v_request public.parking_booking_permission_requests%rowtype;
  v_actor_name text;
  v_notification_id bigint;
  v_response jsonb;
begin
  select * into v_existing from public.parking_booking_command_dedup where idempotency_key = p_idempotency_key;
  if found then
    if v_existing.actor_telegram_user_id <> p_actor_telegram_user_id or v_existing.action <> 'request_write' then
      raise exception using errcode = '22023', message = 'idempotency_key_reused';
    end if;
    return v_existing.response;
  end if;
  perform public.parking_booking_require_admin(p_actor_telegram_user_id);
  select * into v_state from public.parking_booking_write_state where id = 1 for update;
  if v_state.holder_telegram_user_id = p_actor_telegram_user_id then
    raise exception using errcode = '22023', message = 'already_write_holder';
  end if;
  if v_state.holder_telegram_user_id is null then
    raise exception using errcode = '22023', message = 'write_holder_unavailable';
  end if;

  select coalesce(nullif(trim(concat_ws(' ', first_name, last_name)), ''), case when username is not null then '@' || username else 'Usuario ' || telegram_user_id::text end)
  into v_actor_name from public.telegram_users where telegram_user_id = p_actor_telegram_user_id;

  select * into v_request
  from public.parking_booking_permission_requests
  where request_kind = 'request'
    and requester_telegram_user_id = p_actor_telegram_user_id
    and recipient_telegram_user_id = v_state.holder_telegram_user_id
    and proposed_holder_telegram_user_id = p_actor_telegram_user_id
    and status = 'pending'
  limit 1;

  if not found then
    insert into public.parking_booking_permission_requests(
      request_kind, requester_telegram_user_id, recipient_telegram_user_id,
      proposed_holder_telegram_user_id, holder_at_creation_telegram_user_id, writer_epoch
    ) values (
      'request', p_actor_telegram_user_id, v_state.holder_telegram_user_id,
      p_actor_telegram_user_id, v_state.holder_telegram_user_id, v_state.epoch
    ) returning * into v_request;

    insert into public.parking_booking_notifications(
      recipient_telegram_user_id, notification_type, title, body, permission_request_id,
      payload
    ) values (
      v_state.holder_telegram_user_id, 'write_request', 'Solicitud de Lectura/Escritura',
      v_actor_name || ' solicita el permiso de Lectura/Escritura para gestionar las reservas.',
      v_request.id, jsonb_build_object('request_kind', 'request', 'requester_telegram_user_id', p_actor_telegram_user_id)
    ) returning id into v_notification_id;

    insert into public.parking_booking_admin_events(actor_telegram_user_id, action, entity_type, entity_id, permission_request_id, metadata)
    values (p_actor_telegram_user_id, 'request_write', 'write_permission', p_actor_telegram_user_id::text, v_request.id,
            jsonb_build_object('holder_telegram_user_id', v_state.holder_telegram_user_id, 'writer_epoch', v_state.epoch));
  end if;

  v_response := jsonb_build_object('request', to_jsonb(v_request), 'notification_id', v_notification_id);
  insert into public.parking_booking_command_dedup(idempotency_key, actor_telegram_user_id, action, response)
  values (p_idempotency_key, p_actor_telegram_user_id, 'request_write', v_response);
  return v_response;
end;
$$;

create or replace function public.parking_booking_offer_transfer(
  p_actor_telegram_user_id bigint,
  p_writer_epoch bigint,
  p_target_telegram_user_id bigint,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_existing public.parking_booking_command_dedup%rowtype;
  v_state public.parking_booking_write_state%rowtype;
  v_request public.parking_booking_permission_requests%rowtype;
  v_actor_name text;
  v_notification_id bigint;
  v_response jsonb;
begin
  select * into v_existing from public.parking_booking_command_dedup where idempotency_key = p_idempotency_key;
  if found then
    if v_existing.actor_telegram_user_id <> p_actor_telegram_user_id or v_existing.action <> 'offer_transfer' then
      raise exception using errcode = '22023', message = 'idempotency_key_reused';
    end if;
    return v_existing.response;
  end if;
  perform public.parking_booking_require_writer(p_actor_telegram_user_id, p_writer_epoch);
  if p_target_telegram_user_id = p_actor_telegram_user_id then raise exception using errcode = '22023', message = 'invalid_transfer_target'; end if;
  if not exists (
    select 1 from public.telegram_users
    where telegram_user_id = p_target_telegram_user_id and active = true and role in ('owner', 'admin')
  ) then raise exception using errcode = '22023', message = 'invalid_transfer_target'; end if;
  select * into v_state from public.parking_booking_write_state where id = 1;
  select coalesce(nullif(trim(concat_ws(' ', first_name, last_name)), ''), case when username is not null then '@' || username else 'Usuario ' || telegram_user_id::text end)
  into v_actor_name from public.telegram_users where telegram_user_id = p_actor_telegram_user_id;

  select * into v_request
  from public.parking_booking_permission_requests
  where request_kind = 'transfer'
    and requester_telegram_user_id = p_actor_telegram_user_id
    and recipient_telegram_user_id = p_target_telegram_user_id
    and proposed_holder_telegram_user_id = p_target_telegram_user_id
    and status = 'pending'
  limit 1;
  if not found then
    insert into public.parking_booking_permission_requests(
      request_kind, requester_telegram_user_id, recipient_telegram_user_id,
      proposed_holder_telegram_user_id, holder_at_creation_telegram_user_id, writer_epoch
    ) values (
      'transfer', p_actor_telegram_user_id, p_target_telegram_user_id,
      p_target_telegram_user_id, p_actor_telegram_user_id, v_state.epoch
    ) returning * into v_request;

    insert into public.parking_booking_notifications(
      recipient_telegram_user_id, notification_type, title, body, permission_request_id, payload
    ) values (
      p_target_telegram_user_id, 'write_transfer', 'Transferencia de Lectura/Escritura',
      v_actor_name || ' quiere transferirte el permiso de Lectura/Escritura de reservas.',
      v_request.id, jsonb_build_object('request_kind', 'transfer', 'requester_telegram_user_id', p_actor_telegram_user_id)
    ) returning id into v_notification_id;

    insert into public.parking_booking_admin_events(actor_telegram_user_id, action, entity_type, entity_id, permission_request_id, metadata)
    values (p_actor_telegram_user_id, 'offer_transfer', 'write_permission', p_target_telegram_user_id::text, v_request.id,
            jsonb_build_object('writer_epoch', v_state.epoch));
  end if;

  v_response := jsonb_build_object('request', to_jsonb(v_request), 'notification_id', v_notification_id);
  insert into public.parking_booking_command_dedup(idempotency_key, actor_telegram_user_id, action, response)
  values (p_idempotency_key, p_actor_telegram_user_id, 'offer_transfer', v_response);
  return v_response;
end;
$$;

create or replace function public.parking_booking_respond_permission(
  p_actor_telegram_user_id bigint,
  p_request_id uuid,
  p_decision text,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_existing public.parking_booking_command_dedup%rowtype;
  v_request public.parking_booking_permission_requests%rowtype;
  v_state_before public.parking_booking_write_state%rowtype;
  v_state_after public.parking_booking_write_state%rowtype;
  v_target_active boolean;
  v_recipient_name text;
  v_status text;
  v_response jsonb;
  v_expired record;
begin
  select * into v_existing from public.parking_booking_command_dedup where idempotency_key = p_idempotency_key;
  if found then
    if v_existing.actor_telegram_user_id <> p_actor_telegram_user_id or v_existing.action <> 'respond_permission' then
      raise exception using errcode = '22023', message = 'idempotency_key_reused';
    end if;
    return v_existing.response;
  end if;
  perform public.parking_booking_require_admin(p_actor_telegram_user_id);
  if p_decision not in ('accept', 'reject') then raise exception using errcode = '22023', message = 'invalid_permission_decision'; end if;
  select * into v_request from public.parking_booking_permission_requests where id = p_request_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'permission_request_not_found'; end if;
  if v_request.recipient_telegram_user_id <> p_actor_telegram_user_id then raise exception using errcode = '42501', message = 'permission_request_not_recipient'; end if;
  if v_request.status <> 'pending' then raise exception using errcode = '22023', message = 'permission_request_resolved'; end if;
  select * into v_state_before from public.parking_booking_write_state where id = 1 for update;

  if v_request.expires_at <= now()
     or v_state_before.epoch <> v_request.writer_epoch
     or (v_request.request_kind = 'request' and v_state_before.holder_telegram_user_id <> p_actor_telegram_user_id)
     or (v_request.request_kind = 'transfer' and v_state_before.holder_telegram_user_id <> v_request.requester_telegram_user_id) then
    update public.parking_booking_permission_requests
    set status = 'expired', responded_by_telegram_user_id = p_actor_telegram_user_id, responded_at = now()
    where id = v_request.id returning status into v_status;
    insert into public.parking_booking_notifications(recipient_telegram_user_id, notification_type, title, body, permission_request_id)
    values (v_request.requester_telegram_user_id, 'permission_expired', 'Solicitud caducada',
            'La solicitud ya no es válida porque el permiso de escritura cambió.', v_request.id);
    v_response := jsonb_build_object('status', 'expired', 'error', 'permission_request_stale');
    insert into public.parking_booking_command_dedup(idempotency_key, actor_telegram_user_id, action, response)
    values (p_idempotency_key, p_actor_telegram_user_id, 'respond_permission', v_response);
    return v_response;
  end if;

  if p_decision = 'reject' then
    update public.parking_booking_permission_requests
    set status = 'rejected', responded_by_telegram_user_id = p_actor_telegram_user_id, responded_at = now()
    where id = v_request.id;
    insert into public.parking_booking_notifications(recipient_telegram_user_id, notification_type, title, body, permission_request_id)
    values (v_request.requester_telegram_user_id, 'permission_rejected', 'Solicitud rechazada',
            'La solicitud de Lectura/Escritura ha sido rechazada.', v_request.id);
    insert into public.parking_booking_admin_events(actor_telegram_user_id, action, entity_type, entity_id, permission_request_id, before_data, after_data)
    values (p_actor_telegram_user_id, 'reject_permission', 'write_permission', v_request.proposed_holder_telegram_user_id::text,
            v_request.id, to_jsonb(v_state_before), to_jsonb(v_state_before));
    v_response := jsonb_build_object('status', 'rejected', 'permission', to_jsonb(v_state_before));
  else
    select exists (
      select 1 from public.telegram_users
      where telegram_user_id = v_request.proposed_holder_telegram_user_id
        and active = true and role in ('owner', 'admin')
    ) into v_target_active;
    if not v_target_active then raise exception using errcode = '22023', message = 'invalid_transfer_target'; end if;

    update public.parking_booking_write_state
    set holder_telegram_user_id = v_request.proposed_holder_telegram_user_id,
        epoch = epoch + 1,
        granted_by_telegram_user_id = p_actor_telegram_user_id,
        granted_at = now(),
        updated_at = now()
    where id = 1 returning * into v_state_after;
    update public.parking_booking_permission_requests
    set status = 'accepted', responded_by_telegram_user_id = p_actor_telegram_user_id, responded_at = now()
    where id = v_request.id;

    for v_expired in
      update public.parking_booking_permission_requests
      set status = 'expired', responded_at = now()
      where status = 'pending' and id <> v_request.id
      returning requester_telegram_user_id, id
    loop
      insert into public.parking_booking_notifications(recipient_telegram_user_id, notification_type, title, body, permission_request_id)
      values (v_expired.requester_telegram_user_id, 'permission_expired', 'Solicitud caducada',
              'La solicitud ha caducado porque cambió el titular de Lectura/Escritura.', v_expired.id);
    end loop;

    select coalesce(nullif(trim(concat_ws(' ', first_name, last_name)), ''), case when username is not null then '@' || username else 'Usuario ' || telegram_user_id::text end)
    into v_recipient_name from public.telegram_users where telegram_user_id = v_request.proposed_holder_telegram_user_id;
    insert into public.parking_booking_notifications(recipient_telegram_user_id, notification_type, title, body, permission_request_id)
    values (v_request.proposed_holder_telegram_user_id, 'permission_accepted', 'Permiso de Lectura/Escritura activo',
            'Ya puedes crear, modificar, importar y eliminar reservas.', v_request.id);
    if v_request.request_kind = 'transfer' then
      insert into public.parking_booking_notifications(recipient_telegram_user_id, notification_type, title, body, permission_request_id)
      values (v_request.requester_telegram_user_id, 'transfer_accepted', 'Transferencia aceptada',
              v_recipient_name || ' ha aceptado el permiso de Lectura/Escritura.', v_request.id);
    end if;
    insert into public.parking_booking_admin_events(actor_telegram_user_id, action, entity_type, entity_id, permission_request_id, before_data, after_data)
    values (p_actor_telegram_user_id, 'accept_permission', 'write_permission', v_request.proposed_holder_telegram_user_id::text,
            v_request.id, to_jsonb(v_state_before), to_jsonb(v_state_after));
    v_response := jsonb_build_object('status', 'accepted', 'permission', to_jsonb(v_state_after));
  end if;

  insert into public.parking_booking_command_dedup(idempotency_key, actor_telegram_user_id, action, response)
  values (p_idempotency_key, p_actor_telegram_user_id, 'respond_permission', v_response);
  return v_response;
end;
$$;

create or replace function public.parking_booking_mark_notifications_read(
  p_actor_telegram_user_id bigint,
  p_notification_ids jsonb
)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_count integer;
begin
  perform public.parking_booking_require_admin(p_actor_telegram_user_id);
  if p_notification_ids is null or jsonb_typeof(p_notification_ids) <> 'array' then
    raise exception using errcode = '22023', message = 'invalid_notification_selection';
  end if;
  update public.parking_booking_notifications
  set read_at = coalesce(read_at, now())
  where recipient_telegram_user_id = p_actor_telegram_user_id
    and id in (select (value #>> '{}')::bigint from jsonb_array_elements(p_notification_ids));
  get diagnostics v_count = row_count;
  return v_count;
exception
  when invalid_text_representation then
    raise exception using errcode = '22023', message = 'invalid_notification_selection';
end;
$$;

create or replace function public.parking_booking_expire_permission_requests()
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_expired record;
  v_count integer := 0;
begin
  for v_expired in
    update public.parking_booking_permission_requests
    set status = 'expired', responded_at = now()
    where status = 'pending' and expires_at <= now()
    returning id, requester_telegram_user_id
  loop
    v_count := v_count + 1;
    insert into public.parking_booking_notifications(recipient_telegram_user_id, notification_type, title, body, permission_request_id)
    values (v_expired.requester_telegram_user_id, 'permission_expired', 'Solicitud caducada',
            'La solicitud de Lectura/Escritura ha caducado sin respuesta.', v_expired.id);
  end loop;
  return v_count;
end;
$$;

create or replace function public.parking_booking_claim_telegram_notifications(p_limit integer)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_result jsonb;
begin
  with candidates as (
    select id
    from public.parking_booking_notifications
    where telegram_sent_at is null
      and (telegram_claimed_at is null or telegram_claimed_at < now() - interval '5 minutes')
      and telegram_attempts < 8
    order by created_at
    for update skip locked
    limit least(greatest(coalesce(p_limit, 10), 1), 25)
  ), claimed as (
    update public.parking_booking_notifications n
    set telegram_claimed_at = now(), telegram_attempts = telegram_attempts + 1, telegram_error = null
    from candidates c
    where n.id = c.id
    returning n.id, n.recipient_telegram_user_id, n.title, n.body, n.notification_type, n.permission_request_id
  )
  select coalesce(jsonb_agg(to_jsonb(claimed)), '[]'::jsonb) into v_result from claimed;
  return v_result;
end;
$$;

create or replace function public.parking_booking_finish_telegram_notification(
  p_notification_id bigint,
  p_success boolean,
  p_error text
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.parking_booking_notifications
  set telegram_sent_at = case when p_success then now() else telegram_sent_at end,
      telegram_claimed_at = null,
      telegram_error = case when p_success then null else left(coalesce(p_error, 'telegram_error'), 500) end
  where id = p_notification_id;
end;
$$;

create or replace function public.parking_booking_repair_writer_after_admin_change()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_replacement bigint;
  v_state public.parking_booking_write_state%rowtype;
  v_expired record;
begin
  if new.active = true and new.role in ('owner', 'admin') then return new; end if;
  select * into v_state from public.parking_booking_write_state where id = 1 for update;
  if v_state.holder_telegram_user_id is distinct from new.telegram_user_id then return new; end if;

  select telegram_user_id into v_replacement
  from public.telegram_users
  where active = true and role = 'owner' and telegram_user_id <> new.telegram_user_id
  order by created_at limit 1;
  if v_replacement is null then
    select telegram_user_id into v_replacement
    from public.telegram_users
    where active = true and role = 'admin' and telegram_user_id <> new.telegram_user_id
    order by created_at limit 1;
  end if;

  update public.parking_booking_write_state
  set holder_telegram_user_id = v_replacement,
      epoch = epoch + 1,
      granted_by_telegram_user_id = null,
      granted_at = now(),
      updated_at = now()
  where id = 1;
  for v_expired in
    update public.parking_booking_permission_requests
    set status = 'expired', responded_at = now()
    where status = 'pending'
    returning id, requester_telegram_user_id
  loop
    insert into public.parking_booking_notifications(recipient_telegram_user_id, notification_type, title, body, permission_request_id)
    values (v_expired.requester_telegram_user_id, 'permission_expired', 'Solicitud caducada',
            'La solicitud ha caducado porque cambió el titular de Lectura/Escritura.', v_expired.id);
  end loop;
  insert into public.parking_booking_admin_events(actor_telegram_user_id, action, entity_type, entity_id, before_data, after_data, metadata)
  values (null, 'repair_writer', 'write_permission', coalesce(v_replacement::text, 'none'), to_jsonb(v_state),
          jsonb_build_object('holder_telegram_user_id', v_replacement, 'epoch', v_state.epoch + 1),
          jsonb_build_object('reason', 'holder_no_longer_active_admin'));
  if v_replacement is not null then
    insert into public.parking_booking_notifications(recipient_telegram_user_id, notification_type, title, body)
    values (v_replacement, 'permission_recovered', 'Permiso de escritura recuperado',
            'El sistema te ha asignado Lectura/Escritura porque el titular anterior dejó de ser administrador activo.');
  end if;
  return new;
end;
$$;

create trigger parking_booking_repair_writer_after_admin_change
after update of role, active on public.telegram_users
for each row
when (old.role is distinct from new.role or old.active is distinct from new.active)
execute function public.parking_booking_repair_writer_after_admin_change();

revoke execute on function public.parking_booking_require_admin(bigint) from public, anon, authenticated;
revoke execute on function public.parking_booking_require_writer(bigint, bigint) from public, anon, authenticated;
revoke execute on function public.parking_booking_normalize_entry(jsonb) from public, anon, authenticated;
revoke execute on function public.parking_booking_dashboard(bigint, text, integer, integer) from public, anon, authenticated;
revoke execute on function public.parking_booking_create(bigint, bigint, uuid, jsonb) from public, anon, authenticated;
revoke execute on function public.parking_booking_update(bigint, bigint, uuid, uuid, bigint, jsonb) from public, anon, authenticated;
revoke execute on function public.parking_booking_delete_many(bigint, bigint, uuid, jsonb) from public, anon, authenticated;
revoke execute on function public.parking_booking_import_commit(bigint, bigint, uuid, uuid, jsonb) from public, anon, authenticated;
revoke execute on function public.parking_booking_request_write(bigint, uuid) from public, anon, authenticated;
revoke execute on function public.parking_booking_offer_transfer(bigint, bigint, bigint, uuid) from public, anon, authenticated;
revoke execute on function public.parking_booking_respond_permission(bigint, uuid, text, uuid) from public, anon, authenticated;
revoke execute on function public.parking_booking_mark_notifications_read(bigint, jsonb) from public, anon, authenticated;
revoke execute on function public.parking_booking_expire_permission_requests() from public, anon, authenticated;
revoke execute on function public.parking_booking_claim_telegram_notifications(integer) from public, anon, authenticated;
revoke execute on function public.parking_booking_finish_telegram_notification(bigint, boolean, text) from public, anon, authenticated;
revoke execute on function public.parking_booking_repair_writer_after_admin_change() from public, anon, authenticated;

grant execute on function public.parking_booking_require_admin(bigint) to service_role;
grant execute on function public.parking_booking_require_writer(bigint, bigint) to service_role;
grant execute on function public.parking_booking_normalize_entry(jsonb) to service_role;
grant execute on function public.parking_booking_dashboard(bigint, text, integer, integer) to service_role;
grant execute on function public.parking_booking_create(bigint, bigint, uuid, jsonb) to service_role;
grant execute on function public.parking_booking_update(bigint, bigint, uuid, uuid, bigint, jsonb) to service_role;
grant execute on function public.parking_booking_delete_many(bigint, bigint, uuid, jsonb) to service_role;
grant execute on function public.parking_booking_import_commit(bigint, bigint, uuid, uuid, jsonb) to service_role;
grant execute on function public.parking_booking_request_write(bigint, uuid) to service_role;
grant execute on function public.parking_booking_offer_transfer(bigint, bigint, bigint, uuid) to service_role;
grant execute on function public.parking_booking_respond_permission(bigint, uuid, text, uuid) to service_role;
grant execute on function public.parking_booking_mark_notifications_read(bigint, jsonb) to service_role;
grant execute on function public.parking_booking_expire_permission_requests() to service_role;
grant execute on function public.parking_booking_claim_telegram_notifications(integer) to service_role;
grant execute on function public.parking_booking_finish_telegram_notification(bigint, boolean, text) to service_role;
