-- Extend owner-only resource observability with Supabase Usage Analytics.
-- Egress remains deliberately excluded. No hard stops are introduced.

alter table public.resource_observability_config
  add column if not exists api_requests_budget bigint null
    check (api_requests_budget is null or api_requests_budget > 0),
  add column if not exists edge_function_invocations_budget bigint null
    check (edge_function_invocations_budget is null or edge_function_invocations_budget > 0);

create table if not exists public.resource_usage_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  api_requests bigint null check (api_requests is null or api_requests >= 0),
  edge_function_invocations bigint null check (edge_function_invocations is null or edge_function_invocations >= 0),
  edge_functions_checked integer not null default 0 check (edge_functions_checked >= 0),
  source text not null default 'supabase_management_api',
  raw_edge_stats jsonb null,
  error_metadata jsonb null
);

alter table public.resource_usage_snapshots enable row level security;
revoke all on table public.resource_usage_snapshots from public, anon, authenticated;
grant all on table public.resource_usage_snapshots to service_role;

create index if not exists resource_usage_snapshots_captured_at_idx
  on public.resource_usage_snapshots (captured_at desc);

create or replace function public.resource_observability_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_cfg public.resource_observability_config%rowtype;
  v_usage public.resource_usage_snapshots%rowtype;
  v_database_bytes bigint;
  v_storage_bytes bigint;
  v_storage_objects bigint;
  v_database_pct numeric;
  v_storage_pct numeric;
  v_api_pct numeric;
  v_edge_pct numeric;
  v_database_status text := 'ok';
  v_storage_status text := 'unconfigured';
  v_api_status text := 'unconfigured';
  v_edge_status text := 'unconfigured';
  v_overall_status text := 'ok';
begin
  select * into v_cfg
  from public.resource_observability_config
  where id = true;

  if not found then
    raise exception 'resource_observability_config_missing';
  end if;

  select * into v_usage
  from public.resource_usage_snapshots
  order by captured_at desc
  limit 1;

  v_database_bytes := pg_database_size(current_database());

  select
    coalesce(sum(
      case
        when metadata ? 'size' and (metadata->>'size') ~ '^[0-9]+$'
          then (metadata->>'size')::bigint
        else 0
      end
    ), 0)::bigint,
    count(*)::bigint
  into v_storage_bytes, v_storage_objects
  from storage.objects;

  v_database_pct := round((v_database_bytes::numeric * 100) / nullif(v_cfg.database_budget_bytes, 0), 2);

  if v_database_pct >= v_cfg.critical_percent then
    v_database_status := 'critical';
  elsif v_database_pct >= v_cfg.warning_percent then
    v_database_status := 'warning';
  end if;

  if v_cfg.storage_budget_bytes is not null then
    v_storage_pct := round((v_storage_bytes::numeric * 100) / nullif(v_cfg.storage_budget_bytes, 0), 2);
    if v_storage_pct >= v_cfg.critical_percent then
      v_storage_status := 'critical';
    elsif v_storage_pct >= v_cfg.warning_percent then
      v_storage_status := 'warning';
    else
      v_storage_status := 'ok';
    end if;
  end if;

  if v_cfg.api_requests_budget is not null and v_usage.api_requests is not null then
    v_api_pct := round((v_usage.api_requests::numeric * 100) / nullif(v_cfg.api_requests_budget, 0), 2);
    if v_api_pct >= v_cfg.critical_percent then v_api_status := 'critical';
    elsif v_api_pct >= v_cfg.warning_percent then v_api_status := 'warning';
    else v_api_status := 'ok';
    end if;
  elsif v_cfg.api_requests_budget is not null then
    v_api_status := 'unavailable';
  end if;

  if v_cfg.edge_function_invocations_budget is not null and v_usage.edge_function_invocations is not null then
    v_edge_pct := round((v_usage.edge_function_invocations::numeric * 100) / nullif(v_cfg.edge_function_invocations_budget, 0), 2);
    if v_edge_pct >= v_cfg.critical_percent then v_edge_status := 'critical';
    elsif v_edge_pct >= v_cfg.warning_percent then v_edge_status := 'warning';
    else v_edge_status := 'ok';
    end if;
  elsif v_cfg.edge_function_invocations_budget is not null then
    v_edge_status := 'unavailable';
  end if;

  if 'critical' = any(array[v_database_status,v_storage_status,v_api_status,v_edge_status]) then
    v_overall_status := 'critical';
  elsif 'warning' = any(array[v_database_status,v_storage_status,v_api_status,v_edge_status]) then
    v_overall_status := 'warning';
  elsif 'unavailable' = any(array[v_api_status,v_edge_status]) then
    v_overall_status := 'partial';
  elsif 'unconfigured' = any(array[v_storage_status,v_api_status,v_edge_status]) then
    v_overall_status := 'needs_configuration';
  end if;

  return jsonb_build_object(
    'generated_at', now(),
    'overall_status', v_overall_status,
    'warning_percent', v_cfg.warning_percent,
    'critical_percent', v_cfg.critical_percent,
    'database', jsonb_build_object(
      'used_bytes', v_database_bytes,
      'budget_bytes', v_cfg.database_budget_bytes,
      'used_percent', v_database_pct,
      'status', v_database_status
    ),
    'storage', jsonb_build_object(
      'used_bytes', v_storage_bytes,
      'objects', v_storage_objects,
      'budget_bytes', v_cfg.storage_budget_bytes,
      'used_percent', v_storage_pct,
      'status', v_storage_status
    ),
    'api_requests', jsonb_build_object(
      'used', v_usage.api_requests,
      'budget', v_cfg.api_requests_budget,
      'used_percent', v_api_pct,
      'status', v_api_status,
      'captured_at', v_usage.captured_at
    ),
    'edge_function_invocations', jsonb_build_object(
      'used', v_usage.edge_function_invocations,
      'budget', v_cfg.edge_function_invocations_budget,
      'used_percent', v_edge_pct,
      'status', v_edge_status,
      'functions_checked', coalesce(v_usage.edge_functions_checked,0),
      'captured_at', v_usage.captured_at
    ),
    'updated_at', v_cfg.updated_at,
    'updated_by_telegram_user_id', v_cfg.updated_by_telegram_user_id
  );
end
$function$;

revoke all on function public.resource_observability_snapshot()
  from public, anon, authenticated;
grant execute on function public.resource_observability_snapshot()
  to service_role;
