create index parking_booking_admin_events_actor_idx
  on public.parking_booking_admin_events(actor_telegram_user_id);
create index parking_booking_admin_events_request_idx
  on public.parking_booking_admin_events(permission_request_id);
create index parking_booking_command_actor_idx
  on public.parking_booking_command_dedup(actor_telegram_user_id);
create index parking_booking_analyses_actor_idx
  on public.parking_booking_import_analyses(created_by_telegram_user_id);
create index parking_booking_batches_actor_idx
  on public.parking_booking_import_batches(created_by_telegram_user_id);
create index parking_booking_notifications_request_idx
  on public.parking_booking_notifications(permission_request_id);
create index parking_booking_requests_original_holder_idx
  on public.parking_booking_permission_requests(holder_at_creation_telegram_user_id);
create index parking_booking_requests_proposed_holder_idx
  on public.parking_booking_permission_requests(proposed_holder_telegram_user_id);
create index parking_booking_requests_responder_idx
  on public.parking_booking_permission_requests(responded_by_telegram_user_id);
create index parking_booking_write_holder_idx
  on public.parking_booking_write_state(holder_telegram_user_id);
create index parking_booking_write_grantor_idx
  on public.parking_booking_write_state(granted_by_telegram_user_id);
create index parking_bookings_import_batch_idx
  on public.parking_bookings(import_batch_id);
create index parking_bookings_created_by_idx
  on public.parking_bookings(created_by_telegram_user_id);
create index parking_bookings_updated_by_idx
  on public.parking_bookings(updated_by_telegram_user_id);
create index parking_bookings_deleted_by_idx
  on public.parking_bookings(deleted_by_telegram_user_id);
