import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const RELEASE_PRODUCT="ParkingMartin-G";
const RELEASE_VERSION="1.4.0";
const RELEASE_BUILD="2026.09.04.04";
const RELEASE_SOURCE_REVISION="e55f6677889900aabbccddeeff00112233445566";
function releaseAttestation(){return new Response(JSON.stringify({ok:true,product:RELEASE_PRODUCT,function:"modern-search-api",version:RELEASE_VERSION,build:RELEASE_BUILD,source_revision:RELEASE_SOURCE_REVISION}),{headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}

const BOT_TOKEN=Deno.env.get("TELEGRAM_BOT_TOKEN")!;const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;const SECRET_KEYS_JSON=Deno.env.get("SUPABASE_SECRET_KEYS");const LEGACY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const ORIGIN="https://jdlc86.github.io";
function key(){if(SECRET_KEYS_JSON){try{const p=JSON.parse(SECRET_KEYS_JSON);if(p?.default)return p.default;const v=Object.values(p??{})[0];if(typeof v==='string')return v}catch{}}if(LEGACY)return LEGACY;throw new Error('no_server_key')}function hdr(extra:Record<string,string>={}){const k=key();return{apikey:k,Authorization:`Bearer ${k}`,...extra}}function cors(){return{"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}function json(x:any,s=200){return new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json",...cors()}})}
function eq(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a[i]^b[i];return x===0}function hexBytes(s:string){if(!/^[0-9a-f]{64}$/i.test(s))return null;const a=new Uint8Array(32);for(let i=0;i<32;i++)a[i]=parseInt(s.slice(i*2,i*2+2),16);return a}async function hmac(k:Uint8Array|string,m:string){const kb=typeof k==='string'?new TextEncoder().encode(k):k,ik=await crypto.subtle.importKey('raw',kb,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',ik,new TextEncoder().encode(m)))}async function auth(initData:string){const p=new URLSearchParams(initData),hash=p.get('hash')||'';p.delete('hash');const check=[...p.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>`${k}=${v}`).join('\n'),sec=await hmac('WebAppData',BOT_TOKEN),calc=await hmac(sec,check),given=hexBytes(hash);if(!given||!eq(calc,given))throw new Error('invalid_init_data');const at=Number(p.get('auth_date')||0);if(!Number.isFinite(at)||Math.abs(Date.now()/1000-at)>79200)throw new Error('expired_init_data');const u=JSON.parse(p.get('user')||'null');if(!u?.id)throw new Error('missing_user');return Number(u.id)}
async function rest(t:string,p:Record<string,string>){const u=new URL(`${SUPABASE_URL}/rest/v1/${t}`);for(const[k,v]of Object.entries(p))u.searchParams.set(k,v);const r=await fetch(u,{headers:hdr({Accept:'application/json'})});if(!r.ok)throw new Error(await r.text());return r.json()}async function one(t:string,p:Record<string,string>){return(await rest(t,{...p,limit:'1'}))[0]??null}async function insert(t:string,b:any){const r=await fetch(`${SUPABASE_URL}/rest/v1/${t}`,{method:'POST',headers:hdr({'Content-Type':'application/json',Prefer:'return=minimal'}),body:JSON.stringify(b)});if(!r.ok)throw new Error(await r.text())}
async function rpc(name:string,body:any){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:hdr({'Content-Type':'application/json'}),body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||'rpc_failed');return d}
async function insertReturning(t:string,b:any){const r=await fetch(`${SUPABASE_URL}/rest/v1/${t}`,{method:'POST',headers:hdr({'Content-Type':'application/json',Prefer:'return=representation'}),body:JSON.stringify(b)});if(!r.ok)throw new Error(await r.text());return (await r.json())[0]}
async function cancelActiveSearch(wid:string,uid:number){const rows=await rest('operation_flow_sessions',{worker_id:`eq.${wid}`,flow_type:'eq.search',status:'eq.active',select:'id'});for(const s of rows)await rpc('cancel_operation_flow_session',{p_session_id:s.id,p_worker_id:wid,p_telegram_user_id:uid,p_flow_type:'search'})}
async function createSearchSession(plate:string,v:any,w:any,uid:number){await cancelActiveSearch(w.id,uid);return insertReturning('operation_flow_sessions',{flow_type:'search',normalized_plate:plate,vehicle_id:v.id,worker_id:w.id,telegram_user_id:uid,status:'active',current_step:'result'})}

const norm=(s:string)=>s.toUpperCase().replace(/[^A-Z0-9]/g,'');async function ctx(uid:number){const u=await one('telegram_users',{telegram_user_id:`eq.${uid}`,active:'eq.true',select:'telegram_user_id,role'});if(!u)throw new Error('not_authorized');const w=await one('workers',{telegram_user_id:`eq.${uid}`,active:'eq.true',select:'id,full_name'});if(!w)throw new Error('worker_not_found');return{u,w}}
Deno.serve(async req=>{const requestUrl=new URL(req.url);if(req.method==='GET'&&requestUrl.searchParams.get("attest")==="1")return releaseAttestation();if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors()});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const origin=req.headers.get('Origin');if(origin&&origin!==ORIGIN)return json({ok:false,error:'origin_not_allowed'},403);const b=await req.json(),uid=await auth(String(b.initData||'')),{w}=await ctx(uid),action=String(b.action||'search');if(action==='cancel_session'){const id=String(b.flow_session_id||'');if(!id)return json({ok:true,cancelled:false});const d=await rpc('cancel_operation_flow_session',{p_session_id:id,p_worker_id:w.id,p_telegram_user_id:uid,p_flow_type:'search'});return json(d)}const plate=norm(String(b.plate||''));if(plate.length<4)return json({ok:false,error:'invalid_plate'},400);const v=await one('vehicles',{normalized_plate:`eq.${plate}`,select:'id,plate,status,current_lat,current_lng,current_accuracy_m,current_location_text,parked_at,last_updated_by'});if(!v||v.status!=='parked')return json({ok:false,error:'not_parked'},404);const pe=await one('parking_events',{vehicle_id:`eq.${v.id}`,operation:'eq.park',select:'created_at,worker_id,location_text,latitude,longitude,accuracy_m',order:'created_at.desc'});let parkedBy=null;if(pe?.worker_id)parkedBy=(await one('workers',{id:`eq.${pe.worker_id}`,select:'full_name'}))?.full_name??null;const s=await createSearchSession(plate,v,w,uid);await insert('parking_events',{vehicle_id:v.id,worker_id:w.id,operation:'lookup',latitude:v.current_lat??null,longitude:v.current_lng??null,accuracy_m:v.current_accuracy_m??null,location_text:v.current_location_text??'Consulta desde App Moderna',metadata:{source:'modern_search',telegram_user_id:uid,flow_session_id:s.id}});return json({ok:true,flow_session_id:s.id,vehicle:{id:v.id,plate:v.plate,status:v.status,latitude:v.current_lat,longitude:v.current_lng,accuracy_m:v.current_accuracy_m,location_text:v.current_location_text,parked_at:v.parked_at??pe?.created_at??null,parked_by:parkedBy}})}catch(e){const m=String((e as Error)?.message||e);console.error(m);return json({ok:false,error:m},m==='not_authorized'?403:400)}});